pub mod model;
pub mod registry;
pub mod sound;

use std::collections::{HashMap, HashSet};
use std::sync::OnceLock;

use azalea_block::BlockState;
use azalea_core::position::BlockPos;
use glam::DVec3;

use crate::physics::block_shape::{LocalBox, compute_outline, compute_shape};

/// Compact per-state property map: `(key, value)` pairs sorted by key. States
/// have at most ~10 properties, so binary search on a boxed slice beats a
/// `HashMap` in both footprint and lookup cost.
pub struct PropMap(Box<[(&'static str, &'static str)]>);

impl PropMap {
    fn from_pairs(mut pairs: Vec<(&'static str, &'static str)>) -> Self {
        pairs.sort_unstable_by_key(|&(k, _)| k);
        Self(pairs.into_boxed_slice())
    }

    pub fn get(&self, key: &str) -> Option<&'static str> {
        self.0
            .binary_search_by_key(&key, |&(k, _)| k)
            .ok()
            .map(|i| self.0[i].1)
    }

    pub fn entries(&self) -> impl Iterator<Item = (&'static str, &'static str)> + '_ {
        self.0.iter().copied()
    }
}

/// The two behavior fields the client reads (from vanilla `BlockBehaviour`).
#[derive(Clone, Copy)]
pub struct BlockBehavior {
    pub destroy_time: f32,
    pub requires_correct_tool_for_drops: bool,
}

const DEFAULT_BEHAVIOR: BlockBehavior = BlockBehavior {
    destroy_time: 0.0,
    requires_correct_tool_for_drops: false,
};

/// A face-occlusion shape projected onto the face plane as a 16x16 bit grid;
/// `mask[v]` holds row `v`'s bits. Generated by `just stategen`.
pub type FaceMask = [u16; 16];

/// Per-state light properties (vanilla `BlockBehaviour.BlockStateBase`'s
/// baked light cache), loaded from the per-version table generated by
/// `tools/stategen` running vanilla's own code.
#[derive(Clone, Copy)]
pub struct LightProps {
    pub emission: u8,
    pub dampening: u8,
    /// Unconsumed at runtime (vanilla only folds it into `dampening` at
    /// bake time); carried for parity with the vanilla property set.
    #[allow(dead_code)]
    pub propagates_skylight_down: bool,
    pub can_occlude: bool,
    pub use_shape_for_light_occlusion: bool,
    /// Per-face occlusion masks in vanilla `Direction` ordinal order (DOWN,
    /// UP, NORTH, SOUTH, WEST, EAST); `Some` exactly when `can_occlude &&
    /// use_shape_for_light_occlusion`.
    pub face_occlusion: Option<&'static [FaceMask; 6]>,
}

/// Unknown states occlude fully, matching vanilla's bedrock fallback for
/// out-of-range light-engine reads.
const BEDROCK_LIGHT: LightProps = LightProps {
    emission: 0,
    dampening: 15,
    propagates_skylight_down: false,
    can_occlude: true,
    use_shape_for_light_occlusion: false,
    face_occlusion: None,
};

#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum BonemealParticleType {
    NeighborSpreader,
    Grower,
}

#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum FluidKind {
    Empty,
    Water,
    Lava,
}

/// Fluid content of a block state, matching vanilla `FluidState`: sources and
/// waterlogged blocks are amount 8; flowing fluid is `8 - level`; falling
/// fluid (level >= 8) renders/behaves as a full column.
#[derive(Clone, Copy)]
pub struct Fluid {
    pub kind: FluidKind,
    pub amount: u8,
    /// Not consumed yet; kept for vanilla parity (falling columns behave as
    /// full sources in flow/height logic).
    #[allow(dead_code)]
    pub falling: bool,
}

const NO_FLUID: Fluid = Fluid {
    kind: FluidKind::Empty,
    amount: 0,
    falling: false,
};

const FULL_WATER: Fluid = Fluid {
    kind: FluidKind::Water,
    amount: 8,
    falling: false,
};

impl Fluid {
    pub fn height(&self) -> f32 {
        self.amount as f32 / 9.0
    }

    pub fn is_source(&self) -> bool {
        self.kind != FluidKind::Empty && self.amount == 8 && !self.falling
    }
}

/// Per-state block data loaded from the per-version table generated by
/// `tools/blockgen` from Mojang's data-generator report. Hot paths (meshing
/// classifies and textures every block) index this directly.
struct BlockData {
    id: &'static str,
    default_state: BlockState,
    properties: PropMap,
    behavior: BlockBehavior,
    /// Collision shape; see `block_shape::partial_shape` for the encoding.
    shape: Option<Box<[LocalBox]>>,
    /// Outline shape (vanilla `getShape`) where it differs from `shape`; `None`
    /// means the two agree and the collision shape doubles as the outline.
    outline: Option<Box<[LocalBox]>>,
    /// 26.2 BlockBehaviour randomized XZ offset maximum; zero for other
    /// versions.
    max_horizontal_offset: f32,
    is_air: bool,
    /// Vanilla particle-provider metadata, optional for pre-metadata generated
    /// tables.
    map_color_rgb: Option<u32>,
    falling_dust_rgb: Option<u32>,
    spawn_terrain_particles: Option<bool>,
    render_shape_invisible: Option<bool>,
    solid_render: Option<bool>,
    is_leaves_block: bool,
    liquid_block_container: Option<bool>,
    can_place_liquid_water: Option<bool>,
    bonemeal_type: Option<u8>,
    bonemeal_particle_offset: [i32; 3],
    collision_shape_full_block: Option<bool>,
    can_be_replaced_by_water: Option<bool>,
    dynamic_shape: bool,
    shape_max_y_32nds: Option<u8>,
    /// Vanilla `hasCollision` (`BlockBehaviour.Properties.noCollision()`).
    collides: bool,
    /// Approximate `BlockStateBase.blocksMotion`: legacy solidity, except
    /// cobweb and bamboo sapling (dynamic powder snow is not solid).
    blocks_motion: bool,
    /// Vanilla BlockBehaviour's replaceable flag, not context-dependent
    /// merging.
    replaceable: bool,
    fluid: Fluid,
    light: LightProps,
}

#[derive(serde::Deserialize)]
struct BlockFile {
    version: String,
    state_count: u32,
    blocks: Vec<BlockEntry>,
}

#[derive(serde::Deserialize)]
struct BlockEntry {
    name: String,
    first_id: u32,
    default_id: u32,
    /// `(key, values)` in state-enumeration order; the last property varies
    /// fastest across consecutive state ids.
    #[serde(default)]
    props: Vec<(String, Vec<String>)>,
}

#[derive(serde::Deserialize)]
struct BehaviorEntry {
    destroy_time: f32,
    requires_correct_tool: bool,
}

#[derive(serde::Deserialize)]
struct ShapeFile {
    version: String,
    state_count: u32,
    verified_states: u32,
    skipped_states: u32,
    context_dependent_states: u32,
    offset_dependent_states: u32,
    oracle_disagreement_states: u32,
    #[allow(dead_code)]
    oracle: String,
    shapes: Vec<Vec<LocalBox>>,
    blocks: Vec<ShapeBlockEntry>,
}

#[derive(serde::Deserialize)]
struct ShapeBlockEntry {
    name: String,
    first_id: u32,
    props: Vec<(String, Vec<String>)>,
    /// `(state offset, collision shape index, outline shape index)`.
    overrides: Vec<(u32, u32, u32)>,
}

#[derive(serde::Deserialize)]
struct StateFile {
    version: String,
    state_count: u32,
    /// Deduped face masks as 64-hex-char strings (16 rows of 4 chars).
    masks: Vec<String>,
    blocks: Vec<StateEntry>,
}

/// Per-block fields; each is a scalar when uniform across the block's
/// states, else one value per state. `f` is 6 mask-dictionary indices —
/// a single tuple when uniform, else a per-state list of tuple-or-null.
#[derive(serde::Deserialize)]
struct StateEntry {
    name: String,
    e: ScalarOrPerState,
    d: ScalarOrPerState,
    p: ScalarOrPerState,
    o: ScalarOrPerState,
    u: ScalarOrPerState,
    /// `hasCollision`; block-level in vanilla, so always a scalar.
    c: u8,
    #[serde(default)]
    f: Option<serde_json::Value>,
    #[serde(default)]
    m: Option<ScalarOrPerStateU32>,
    #[serde(default)]
    q: Option<ScalarOrPerStateU32>,
    #[serde(default)]
    s: Option<ScalarOrPerState>,
    #[serde(default)]
    r: Option<ScalarOrPerState>,
    #[serde(default)]
    t: Option<ScalarOrPerState>,
    #[serde(default)]
    v: Option<ScalarOrPerState>,
    #[serde(default)]
    l: Option<ScalarOrPerState>,
    /// Exact Java `block instanceof LiquidBlockContainer` type identity.
    #[serde(default)]
    k: Option<ScalarOrPerState>,
    /// Java `LiquidBlockContainer.canPlaceLiquid(null, ..., Fluids.WATER)`.
    #[serde(default)]
    n: Option<ScalarOrPerState>,
    /// Exact Java `BonemealableBlock.Type`: 0 not bonemealable, 1 spreader, 2
    /// grower.
    #[serde(default)]
    b: Option<ScalarOrPerState>,
    /// Exact `getParticlePos(BlockPos.ZERO)` offset, uniform tuple or per-state
    /// tuples.
    #[serde(default)]
    g: Option<ScalarOrPerStateOffset>,
    /// Java `isCollisionShapeFullBlock(EmptyBlockGetter, ZERO)`; exact shape
    /// union.
    #[serde(default)]
    h: Option<ScalarOrPerState>,
    /// Exact Java `BlockState.canBeReplaced(Fluids.WATER)` result.
    #[serde(default)]
    w: Option<ScalarOrPerState>,
    #[serde(default)]
    i: Option<ScalarOrPerState>,
    /// `getShape(EmptyBlockGetter, ZERO).max(Y)` in thirty-seconds; 255 is
    /// empty.
    #[serde(default)]
    j: Option<ScalarOrPerState>,
}

#[derive(serde::Deserialize)]
#[serde(untagged)]
enum ScalarOrPerState {
    One(u8),
    Many(Vec<u8>),
}

#[derive(serde::Deserialize)]
#[serde(untagged)]
enum ScalarOrPerStateOffset {
    One([i32; 3]),
    Many(Vec<[i32; 3]>),
}

impl ScalarOrPerStateOffset {
    fn get(&self, offset: usize) -> [i32; 3] {
        match self {
            Self::One(v) => *v,
            Self::Many(vs) => vs[offset],
        }
    }
}

#[derive(serde::Deserialize)]
#[serde(untagged)]
enum ScalarOrPerStateU32 {
    One(u32),
    Many(Vec<u32>),
}

impl ScalarOrPerStateU32 {
    fn get(&self, offset: usize) -> u32 {
        match self {
            Self::One(v) => *v,
            Self::Many(vs) => vs[offset],
        }
    }
}

impl ScalarOrPerState {
    fn get(&self, offset: usize) -> u8 {
        match self {
            Self::One(v) => *v,
            Self::Many(vs) => vs[offset],
        }
    }
}

/// One version's embedded block tables. `blocks` is the state layout (ids and
/// properties from the data-generator report); `state` (`just stategen`)
/// holds the per-state values vanilla bakes at runtime, dumped by running its
/// own code.
struct EmbeddedBlocks {
    protocol: i32,
    blocks: &'static str,
    state: &'static str,
    shapes: Option<&'static str>,
}

/// The per-version state tables and optional vanilla-verified shape overrides.
macro_rules! embedded_blocks {
    ($protocol:expr, $version:literal) => {
        EmbeddedBlocks {
            protocol: $protocol,
            blocks: include_str!(concat!("data/blocks-", $version, ".json")),
            state: include_str!(concat!("data/state-", $version, ".json")),
            shapes: None,
        }
    };
    ($protocol:expr, $version:literal, $shape_version:literal) => {
        EmbeddedBlocks {
            protocol: $protocol,
            blocks: include_str!(concat!("data/blocks-", $version, ".json")),
            state: include_str!(concat!("data/state-", $version, ".json")),
            shapes: Some(include_str!(concat!(
                "data/shapes-",
                $shape_version,
                ".json"
            ))),
        }
    };
}

/// Per-protocol block-state data, the native version at [`NATIVE_SLOT`].
const BLOCK_DATA: &[EmbeddedBlocks] = &[
    embedded_blocks!(pomme_protocol::version::NATIVE.protocol, "26.2", "26.2"),
    embedded_blocks!(777, "26.3"),
    embedded_blocks!(775, "26.1"),
    embedded_blocks!(774, "1.21.11"),
    embedded_blocks!(773, "1.21.10"),
    embedded_blocks!(772, "1.21.8"),
    embedded_blocks!(770, "1.21.5"),
    embedded_blocks!(769, "1.21.4"),
    embedded_blocks!(768, "1.21.3"),
    embedded_blocks!(767, "1.21.1"),
    embedded_blocks!(765, "1.20.4"),
    embedded_blocks!(764, "1.20.2"),
    embedded_blocks!(763, "1.20.1"),
];

/// Protocols whose block set is identical to a newer embedded version's (no
/// blocks added between them); they share that version's slot instead of
/// building a second copy of the same table. The slot also serves the state
/// table, so an alias requires the two versions' `generated/state.json`
/// dumps to be identical as well, not just the block list.
const SHARED_BLOCK_DATA: &[(i32, i32)] = &[
    // 1.21.7 added no blocks.
    (771, 772),
    // 1.21's trial-chamber blocks already existed in 1.20.6.
    (766, 767),
];

/// One lazily-built table per embedded data file; `ACTIVE_TABLE` indexes the
/// protocol currently spoken (see [`set_active_protocol`]).
static BLOCK_TABLES: [OnceLock<Vec<BlockData>>; BLOCK_DATA.len()] =
    [const { OnceLock::new() }; BLOCK_DATA.len()];
/// The [`BLOCK_DATA`] slot holding the native version's tables: the initial
/// active table and the fallback for protocols without their own data.
const NATIVE_SLOT: usize = 0;
static ACTIVE_TABLE: std::sync::atomic::AtomicUsize =
    std::sync::atomic::AtomicUsize::new(NATIVE_SLOT);

#[cfg(test)]
static TEST_PROTOCOL_LOCK: std::sync::Mutex<()> = std::sync::Mutex::new(());

#[cfg(test)]
pub(crate) struct TestProtocolGuard {
    _lock: std::sync::MutexGuard<'static, ()>,
}

#[cfg(test)]
impl Drop for TestProtocolGuard {
    fn drop(&mut self) {
        ACTIVE_TABLE.store(NATIVE_SLOT, std::sync::atomic::Ordering::Release);
    }
}

#[cfg(test)]
pub(crate) fn test_protocol_guard() -> TestProtocolGuard {
    let lock = TEST_PROTOCOL_LOCK
        .lock()
        .unwrap_or_else(std::sync::PoisonError::into_inner);
    set_active_protocol(pomme_protocol::version::NATIVE.protocol);
    TestProtocolGuard { _lock: lock }
}

/// Vanilla getFluidState overrides on blocks without a `waterlogged` property.
const IMPLICIT_WATER: [&str; 4] = ["seagrass", "tall_seagrass", "kelp", "kelp_plant"];

/// Loads the block-state table for the launched game version. Must be called
/// once at startup before any world/render code runs.
pub fn init(version: &str) {
    let protocol = pomme_protocol::ProtocolVersion::from_name(version)
        .map(|v| v.protocol)
        .unwrap_or_else(|| {
            tracing::warn!(
                "no block-state data for version {version}, using {} — expect state drift",
                pomme_protocol::version::NATIVE.name
            );
            pomme_protocol::version::NATIVE.protocol
        });
    set_active_protocol(protocol);
}

/// Switches the active table to the given protocol's, building it on first
/// use, so state ids from the wire are interpreted natively in that
/// version's id space (no chunk remapping). Patch releases sharing a
/// protocol number (26.1 through 26.1.2 are all 775) get the same table.
/// Only safe between worlds — meshes built against the previous table
/// interpret ids in the old id space.
pub fn set_active_protocol(protocol: i32) {
    let slot = prewarm_protocol(protocol);
    ACTIVE_TABLE.store(slot, std::sync::atomic::Ordering::Release);
}

/// Builds the given protocol's table if it isn't already, without switching
/// to it; safe at any time (e.g. from a server-list ping, ahead of the join).
pub fn prewarm_protocol(protocol: i32) -> usize {
    let slot = block_data_slot(protocol).unwrap_or(NATIVE_SLOT);
    BLOCK_TABLES[slot].get_or_init(|| build_table(&BLOCK_DATA[slot]));
    slot
}

/// Resolve a protocol's block registry entry index to its identity using the
/// same versioned generated block table used for that protocol's states.
pub fn block_name_for_registry_id(protocol: i32, id: u32) -> Option<String> {
    let slot = block_data_slot(protocol)?;
    let file: BlockFile = serde_json::from_str(BLOCK_DATA[slot].blocks).ok()?;
    file.blocks.get(id as usize).map(|entry| entry.name.clone())
}

/// The `BLOCK_DATA` slot serving a protocol, through `SHARED_BLOCK_DATA`.
fn block_data_slot(protocol: i32) -> Option<usize> {
    let protocol = SHARED_BLOCK_DATA
        .iter()
        .find(|&&(p, _)| p == protocol)
        .map_or(protocol, |&(_, shared)| shared);
    BLOCK_DATA.iter().position(|d| d.protocol == protocol)
}

fn load_behaviors() -> HashMap<String, BehaviorEntry> {
    serde_json::from_str(include_str!("data/block_behavior.json"))
        .expect("invalid block-behavior data")
}

fn validate_shape_boxes(shapes: &[Vec<LocalBox>]) {
    for (shape_index, shape) in shapes.iter().enumerate() {
        for (box_index, bounds) in shape.iter().enumerate() {
            assert!(
                bounds.iter().all(|coordinate| coordinate.is_finite()),
                "shape {shape_index} box {box_index} has a non-finite coordinate"
            );
            for axis in 0..3 {
                assert!(
                    bounds[axis] <= bounds[axis + 3],
                    "shape {shape_index} box {box_index} has inverted bounds on axis {axis}"
                );
            }
        }
    }
}

fn build_table(data: &EmbeddedBlocks) -> Vec<BlockData> {
    let file: BlockFile = serde_json::from_str(data.blocks).expect("invalid block-state data");
    assert_eq!(
        pomme_protocol::ProtocolVersion::from_name(&file.version).map(|v| v.protocol),
        Some(data.protocol),
        "block data for {} is keyed to protocol {}",
        file.version,
        data.protocol
    );
    let behaviors = load_behaviors();
    let state_file: StateFile = serde_json::from_str(data.state).expect("invalid state data");
    assert_eq!(
        state_file.version, file.version,
        "state data is for a different version"
    );
    assert_eq!(
        state_file.state_count, file.state_count,
        "state data state count mismatch"
    );
    assert_eq!(
        state_file.blocks.len(),
        file.blocks.len(),
        "state data block count mismatch"
    );
    let shape_file = data.shapes.map(|json| {
        let shapes: ShapeFile = serde_json::from_str(json).expect("invalid block-shape data");
        validate_shape_boxes(&shapes.shapes);
        assert_eq!(
            shapes.version, file.version,
            "shape data is for a different version"
        );
        assert_eq!(
            shapes.state_count, file.state_count,
            "shape data state count mismatch"
        );
        assert_eq!(
            shapes.verified_states + shapes.skipped_states,
            shapes.state_count,
            "shape data coverage mismatch"
        );
        assert_eq!(
            shapes.context_dependent_states
                + shapes.offset_dependent_states
                + shapes.oracle_disagreement_states,
            shapes.skipped_states,
            "shape data skip counts mismatch"
        );
        assert_eq!(
            shapes.blocks.len(),
            file.blocks.len(),
            "shape data block count mismatch"
        );
        shapes
    });
    let masks: &'static [FaceMask] = Vec::leak(
        state_file
            .masks
            .iter()
            .map(|hex| decode_face_mask(hex))
            .collect(),
    );
    // The same handful of 6-mask tuples repeats across thousands of states;
    // dedupe them into leaked statics so each state stores one pointer.
    let mut tuples: HashMap<[u32; 6], &'static [FaceMask; 6]> = HashMap::new();
    let mut tuple = |indices: [u32; 6]| -> &'static [FaceMask; 6] {
        tuples
            .entry(indices)
            .or_insert_with(|| Box::leak(Box::new(indices.map(|i| masks[i as usize]))))
    };

    let mut interner: HashSet<&'static str> = HashSet::new();
    let mut intern = |s: &str| -> &'static str {
        match interner.get(s) {
            Some(&e) => e,
            None => {
                let leaked: &'static str = Box::leak(s.to_string().into_boxed_str());
                interner.insert(leaked);
                leaked
            }
        }
    };

    let mut table: Vec<BlockData> = Vec::with_capacity(file.state_count as usize);
    for (block_index, (block, state_entry)) in
        file.blocks.iter().zip(&state_file.blocks).enumerate()
    {
        assert_eq!(
            block.first_id,
            table.len() as u32,
            "block-state data not dense at '{}'",
            block.name
        );
        let shape_block = shape_file.as_ref().map(|file| {
            let entry = &file.blocks[block_index];
            assert_eq!(entry.name, block.name, "shape block order mismatch");
            assert_eq!(
                entry.first_id, block.first_id,
                "shape block state id mismatch"
            );
            assert_eq!(entry.props, block.props, "shape block properties mismatch");
            entry
        });
        assert_eq!(
            state_entry.name, block.name,
            "state data out of order at '{}'",
            block.name
        );
        let name = intern(&block.name);
        let behavior = match behaviors.get(&block.name) {
            Some(b) => BlockBehavior {
                destroy_time: b.destroy_time,
                requires_correct_tool_for_drops: b.requires_correct_tool,
            },
            None => {
                tracing::warn!("no behavior entry for block '{}', using defaults", name);
                DEFAULT_BEHAVIOR
            }
        };
        let props: Vec<(&'static str, Vec<&'static str>)> = block
            .props
            .iter()
            .map(|(k, vs)| (intern(k), vs.iter().map(|v| intern(v)).collect()))
            .collect();
        let is_air = matches!(block.name.as_str(), "air" | "cave_air" | "void_air");
        let collides = state_entry.c != 0;

        let count: u32 = props.iter().map(|(_, vs)| vs.len() as u32).product();
        assert!((block.first_id..block.first_id + count).contains(&block.default_id));
        if let Some(entry) = shape_block {
            let mut previous = None;
            for shape in &entry.overrides {
                assert!(
                    shape.0 < count,
                    "shape offset out of range for {}",
                    block.name
                );
                assert!(
                    previous.map_or(true, |offset| shape.0 > offset),
                    "shape offsets not strictly ordered for {}",
                    block.name
                );
                previous = Some(shape.0);
            }
        }
        let default_state =
            BlockState::try_from(block.default_id).expect("default state fits id repr");
        let face_indices = light_face_indices(state_entry, count as usize);
        for offset in 0..count {
            let mut pairs = Vec::with_capacity(props.len());
            let mut stride = count;
            for (key, values) in &props {
                stride /= values.len() as u32;
                pairs.push((*key, values[(offset / stride) as usize % values.len()]));
            }
            let properties = PropMap::from_pairs(pairs);
            let fluid = state_fluid(name, &properties);
            let override_shape = shape_block.and_then(|block| {
                block
                    .overrides
                    .binary_search_by_key(&offset, |shape| shape.0)
                    .ok()
                    .map(|index| &block.overrides[index])
            });
            let (shape, outline) = if let Some(exact) = override_shape {
                let collision = shape_file
                    .as_ref()
                    .expect("shape override requires its shape file")
                    .shapes
                    .get(exact.1 as usize)
                    .unwrap_or_else(|| {
                        panic!("collision shape index out of range for {}", block.name)
                    })
                    .clone();
                let outline = shape_file
                    .as_ref()
                    .expect("shape override requires its shape file")
                    .shapes
                    .get(exact.2 as usize)
                    .unwrap_or_else(|| {
                        panic!("outline shape index out of range for {}", block.name)
                    })
                    .clone();
                let full_cube = [[0.0, 0.0, 0.0, 1.0, 1.0, 1.0]];
                let collision_field = (collision.as_slice() != full_cube.as_slice())
                    .then(|| collision.clone().into_boxed_slice());
                let outline_field = (outline != collision).then(|| outline.into_boxed_slice());
                (collision_field, outline_field)
            } else if file.version != "26.2"
                && matches!(
                    name,
                    "mangrove_propagule"
                        | "dandelion"
                        | "golden_dandelion"
                        | "torchflower"
                        | "poppy"
                        | "blue_orchid"
                        | "allium"
                        | "azure_bluet"
                        | "red_tulip"
                        | "orange_tulip"
                        | "white_tulip"
                        | "pink_tulip"
                        | "oxeye_daisy"
                        | "cornflower"
                        | "wither_rose"
                        | "lily_of_the_valley"
                        | "bamboo_sapling"
                        | "bamboo"
                        | "pointed_dripstone"
                        | "sulfur_spike"
                        | "open_eyeblossom"
                        | "closed_eyeblossom"
                )
            {
                (None, None)
            } else {
                (
                    compute_shape(name, &properties).map(Vec::into_boxed_slice),
                    compute_outline(name, &properties).map(Vec::into_boxed_slice),
                )
            };
            let max_horizontal_offset = if file.version == "26.2" {
                match name {
                    "mangrove_propagule" | "dandelion" | "golden_dandelion" | "torchflower"
                    | "poppy" | "blue_orchid" | "allium" | "azure_bluet" | "red_tulip"
                    | "orange_tulip" | "white_tulip" | "pink_tulip" | "oxeye_daisy"
                    | "cornflower" | "wither_rose" | "lily_of_the_valley" | "bamboo_sapling"
                    | "bamboo" | "open_eyeblossom" | "closed_eyeblossom" => 0.25,
                    "pointed_dripstone" | "sulfur_spike" => 0.125,
                    _ => 0.0,
                }
            } else {
                0.0
            };
            let light = LightProps {
                emission: state_entry.e.get(offset as usize),
                dampening: state_entry.d.get(offset as usize),
                propagates_skylight_down: state_entry.p.get(offset as usize) != 0,
                can_occlude: state_entry.o.get(offset as usize) != 0,
                use_shape_for_light_occlusion: state_entry.u.get(offset as usize) != 0,
                face_occlusion: face_indices[offset as usize].map(&mut tuple),
            };
            // Vanilla's default legacySolid uses cached collision bounds;
            // forceSolidOn/Off require additional registry data.
            let blocks_motion = collides
                && !matches!(name, "cobweb" | "bamboo_sapling" | "powder_snow")
                && match shape.as_deref() {
                    Some(boxes) if boxes.is_empty() => false,
                    Some(boxes) => {
                        let min = [0, 1, 2].map(|axis| {
                            boxes.iter().map(|b| b[axis]).fold(f64::INFINITY, f64::min)
                        });
                        let max = [3, 4, 5].map(|axis| {
                            boxes
                                .iter()
                                .map(|b| b[axis])
                                .fold(f64::NEG_INFINITY, f64::max)
                        });
                        let (x, y, z) = (max[0] - min[0], max[1] - min[1], max[2] - min[2]);
                        (x + y + z) / 3.0 >= 0.729_166_666_666_666_6 || y >= 1.0
                    }
                    None => true,
                };
            table.push(BlockData {
                id: name,
                default_state,
                properties,
                behavior,
                shape,
                outline,
                max_horizontal_offset,
                is_air,
                map_color_rgb: state_entry.m.as_ref().map(|v| v.get(offset as usize)),
                falling_dust_rgb: state_entry.q.as_ref().map(|v| v.get(offset as usize)),
                spawn_terrain_particles: state_entry
                    .s
                    .as_ref()
                    .map(|v| v.get(offset as usize) != 0),
                render_shape_invisible: state_entry.r.as_ref().map(|v| v.get(offset as usize) != 0),
                solid_render: state_entry.t.as_ref().map(|v| v.get(offset as usize) != 0),
                is_leaves_block: state_entry
                    .l
                    .as_ref()
                    .is_some_and(|v| v.get(offset as usize) != 0),
                liquid_block_container: state_entry.k.as_ref().map(|v| v.get(offset as usize) != 0),
                can_place_liquid_water: state_entry.n.as_ref().map(|v| v.get(offset as usize) != 0),
                bonemeal_type: state_entry
                    .b
                    .as_ref()
                    .map(|v| v.get(offset as usize))
                    .filter(|&kind| kind != 0),
                bonemeal_particle_offset: state_entry
                    .g
                    .as_ref()
                    .map(|v| v.get(offset as usize))
                    .unwrap_or([0, 0, 0]),
                collision_shape_full_block: state_entry
                    .h
                    .as_ref()
                    .map(|v| v.get(offset as usize) != 0),
                can_be_replaced_by_water: state_entry
                    .w
                    .as_ref()
                    .map(|v| v.get(offset as usize) != 0),
                dynamic_shape: state_entry
                    .i
                    .as_ref()
                    .is_some_and(|v| v.get(offset as usize) != 0),
                shape_max_y_32nds: state_entry.j.as_ref().map(|v| v.get(offset as usize)),
                collides,
                blocks_motion: state_entry
                    .v
                    .as_ref()
                    .map(|v| v.get(offset as usize) != 0)
                    .unwrap_or(blocks_motion),
                replaceable: registry::block_is_replaceable(name),
                fluid,
                light,
            });
        }
    }

    assert_eq!(
        table.len() as u32,
        file.state_count,
        "block-state data table size mismatch for {}",
        file.version
    );
    table
}

fn decode_face_mask(hex: &str) -> FaceMask {
    assert_eq!(hex.len(), 64, "face mask must be 64 hex chars");
    std::array::from_fn(|v| {
        u16::from_str_radix(&hex[v * 4..v * 4 + 4], 16).expect("invalid face-mask hex")
    })
}

/// Expands a light entry's `f` field into per-state mask-dictionary tuples.
fn light_face_indices(entry: &StateEntry, count: usize) -> Vec<Option<[u32; 6]>> {
    let Some(f) = &entry.f else {
        return vec![None; count];
    };
    let arr = f
        .as_array()
        .unwrap_or_else(|| panic!("{}: face-mask field is not an array", entry.name));
    let parse_tuple = |values: &[serde_json::Value]| -> [u32; 6] {
        assert_eq!(values.len(), 6, "{}: face-mask tuple length", entry.name);
        std::array::from_fn(|i| {
            values[i]
                .as_u64()
                .unwrap_or_else(|| panic!("{}: non-numeric face-mask index", entry.name))
                as u32
        })
    };
    if arr.first().is_some_and(serde_json::Value::is_number) {
        // Uniform across the block: a single 6-index tuple.
        return vec![Some(parse_tuple(arr)); count];
    }
    assert_eq!(arr.len(), count, "{}: face-mask entry count", entry.name);
    arr.iter()
        .map(|v| {
            if v.is_null() {
                None
            } else {
                Some(parse_tuple(v.as_array().unwrap_or_else(|| {
                    panic!("{}: face-mask entry is not a tuple", entry.name)
                })))
            }
        })
        .collect()
}

fn state_fluid(name: &'static str, props: &PropMap) -> Fluid {
    match name {
        "water" | "lava" => {
            let level: u8 = props.get("level").and_then(|l| l.parse().ok()).unwrap_or(0);
            let kind = if name == "water" {
                FluidKind::Water
            } else {
                FluidKind::Lava
            };
            if level >= 8 {
                Fluid {
                    kind,
                    amount: 8,
                    falling: true,
                }
            } else {
                Fluid {
                    kind,
                    amount: 8 - level,
                    falling: false,
                }
            }
        }
        "bubble_column" => FULL_WATER,
        _ if IMPLICIT_WATER.contains(&name) => FULL_WATER,
        _ if props.get("waterlogged") == Some("true") => FULL_WATER,
        _ => NO_FLUID,
    }
}

fn table() -> &'static Vec<BlockData> {
    BLOCK_TABLES[ACTIVE_TABLE.load(std::sync::atomic::Ordering::Acquire)]
        .get()
        .expect("world::block::init must be called before use")
}

fn block_data(state: BlockState) -> &'static BlockData {
    static UNKNOWN: std::sync::LazyLock<BlockData> = std::sync::LazyLock::new(|| BlockData {
        id: "unknown",
        default_state: BlockState::AIR,
        properties: PropMap::from_pairs(Vec::new()),
        behavior: DEFAULT_BEHAVIOR,
        shape: None,
        outline: None,
        max_horizontal_offset: 0.0,
        is_air: false,
        map_color_rgb: None,
        falling_dust_rgb: None,
        spawn_terrain_particles: None,
        render_shape_invisible: None,
        solid_render: None,
        is_leaves_block: false,
        liquid_block_container: None,
        can_place_liquid_water: None,
        bonemeal_type: None,
        bonemeal_particle_offset: [0, 0, 0],
        collision_shape_full_block: None,
        can_be_replaced_by_water: None,
        dynamic_shape: false,
        shape_max_y_32nds: None,
        collides: true,
        blocks_motion: true,
        replaceable: false,
        fluid: NO_FLUID,
        light: BEDROCK_LIGHT,
    });
    table().get(u32::from(state) as usize).unwrap_or(&UNKNOWN)
}

/// Every valid block state paired with its cached data, in id order.
fn all_states() -> impl Iterator<Item = (BlockState, &'static BlockData)> {
    table().iter().enumerate().map(|(id, data)| {
        let state = BlockState::try_from(id as u32).expect("table indices fit the id repr");
        (state, data)
    })
}

/// First declared state of the named block, e.g. the light engine's bedrock
/// fallback for unloaded-chunk reads.
pub(crate) fn first_state_of(name: &str) -> Option<BlockState> {
    all_states().find(|(_, d)| d.id == name).map(|(s, _)| s)
}

/// Vanilla default state in the active protocol's id space, not its first
/// state.
pub(crate) fn default_state_of(name: &str) -> Option<BlockState> {
    table()
        .iter()
        .find(|data| data.id == name)
        .map(|data| data.default_state)
}

/// Exact registered-state lookup for serialized block-state properties.
pub(crate) fn state_with_properties(
    name: &str,
    properties: &[(String, String)],
) -> Option<BlockState> {
    all_states()
        .find(|(_, data)| {
            data.id == name
                && data.properties.entries().count() == properties.len()
                && data
                    .properties
                    .entries()
                    .all(|(key, value)| properties.iter().any(|(k, v)| k == key && v == value))
        })
        .map(|(state, _)| state)
}

/// Exact registered state lookup for NBT forms that omit `Properties`.
pub(crate) fn state_without_properties(name: &str) -> Option<BlockState> {
    state_with_properties(name, &[])
}

pub(crate) fn water_source_state() -> BlockState {
    all_states()
        .find(|(_, d)| d.id == "water" && d.properties.get("level") == Some("0"))
        .map(|(state, _)| state)
        .expect("vanilla water source state must exist")
}

/// Converts a wire-side numeric state id, validated against the loaded table.
pub fn try_state(id: u32) -> Option<BlockState> {
    if (id as usize) < table().len() {
        BlockState::try_from(id).ok()
    } else {
        None
    }
}

/// Vanilla LevelChunk's debug-world read override, including in Nether/End.
/// Built once per level from the active protocol table (the vanilla registry
/// order).
#[derive(Clone, Copy)]
pub(crate) struct DebugWorld {
    width: i32,
    height: i32,
    barrier: BlockState,
}

impl DebugWorld {
    pub fn new() -> Self {
        let count = table().len();
        let width = (count as f32).sqrt().ceil() as i32;
        Self {
            width,
            height: count.div_ceil(width as usize) as i32,
            // Barrier's first enumerated state is waterlogged; vanilla uses its dry default.
            barrier: all_states()
                .find(|(_, d)| d.id == "barrier" && d.properties.get("waterlogged") != Some("true"))
                .expect("vanilla debug world requires barrier")
                .0,
        }
    }

    pub fn state(self, x: i32, y: i32, z: i32) -> BlockState {
        if y == 60 {
            return self.barrier;
        }
        if y == 70 && x > 0 && z > 0 && x % 2 != 0 && z % 2 != 0 {
            let (x, z) = (x / 2, z / 2);
            // DebugLevelSource.getBlockStateFor uses inclusive grid bounds.
            if x <= self.width && z <= self.height {
                return try_state((x * self.width + z) as u32).unwrap_or(BlockState::AIR);
            }
        }
        BlockState::AIR
    }
}

pub fn block_id(state: BlockState) -> &'static str {
    block_data(state).id
}

pub fn block_properties(state: BlockState) -> &'static PropMap {
    &block_data(state).properties
}

/// Vanilla 26.2 BlockBehaviour.Properties.offsetType XZ translation.
pub fn block_offset(state: BlockState, pos: BlockPos) -> DVec3 {
    let max = block_data(state).max_horizontal_offset;
    if max == 0.0 {
        return DVec3::ZERO;
    }
    // Mth.getSeed(x, 0, z), with Java's wrapping signed-long arithmetic.
    // Mth.getSeed's first product is int arithmetic before its cast to long;
    // the z product and following polynomial use wrapping Java-long arithmetic.
    let x_seed = i64::from(pos.x.wrapping_mul(3_129_871));
    let z_seed = i64::from(pos.z).wrapping_mul(116_129_781);
    let seed = x_seed ^ z_seed;
    let seed = seed
        .wrapping_mul(seed)
        .wrapping_mul(42_317_861)
        .wrapping_add(seed.wrapping_mul(11))
        >> 16;
    let component = |nibble: u32| {
        // Java divides floats first, then promotes the quotient to double.
        let fraction = (nibble as f32 / 15.0_f32) as f64;
        ((fraction - 0.5) * 0.5).clamp(-f64::from(max), f64::from(max))
    };
    DVec3::new(
        component((seed & 15) as u32),
        0.0,
        component(((seed >> 8) & 15) as u32),
    )
}

pub fn block_behavior(state: BlockState) -> &'static BlockBehavior {
    &block_data(state).behavior
}

/// Vanilla `RedStoneWireBlock.getColorForPower`: dust tint for the state's
/// `power` value.
pub fn redstone_wire_rgb(state: BlockState) -> [f32; 3] {
    static COLORS: std::sync::LazyLock<[[f32; 3]; 16]> = std::sync::LazyLock::new(|| {
        std::array::from_fn(|power| {
            let f = power as f32 / 15.0;
            let red = f * 0.6 + if power > 0 { 0.4 } else { 0.3 };
            let green = (f * f * 0.7 - 0.5).clamp(0.0, 1.0);
            let blue = (f * f * 0.6 - 0.7).clamp(0.0, 1.0);
            [red, green, blue]
        })
    });
    let power: usize = block_properties(state)
        .get("power")
        .and_then(|p| p.parse().ok())
        .unwrap_or(0);
    COLORS[power.min(15)]
}

/// Vanilla `BlockTintSources.stem`: ARGB.color(age * 32, 255 - age * 8, age *
/// 4). The state table carries the canonical `age` property as a decimal
/// string.
pub fn stem_rgb(state: BlockState) -> [f32; 3] {
    let age = block_properties(state)
        .get("age")
        .and_then(|value| value.parse::<u8>().ok())
        .unwrap_or(0)
        .min(7);
    [
        age as f32 * 32.0 / 255.0,
        (255.0 - age as f32 * 8.0) / 255.0,
        age as f32 * 4.0 / 255.0,
    ]
}

/// Java BlockState provider filters backed by BlockBehaviour/Block overrides.
/// The 26.2 source has only barrier and structure_void opt out of terrain
/// particles, while invisible render shapes are the named overrides below.
pub fn should_spawn_terrain_particles(state: BlockState) -> bool {
    block_data(state)
        .spawn_terrain_particles
        .unwrap_or_else(|| !matches!(block_data(state).id, "barrier" | "structure_void"))
}

/// Vanilla `BlockStateBase.isSolidRender`, when generated metadata is
/// available.
pub fn is_solid_render(state: BlockState) -> Option<bool> {
    block_data(state).solid_render
}

/// Java 26.2 `state.getBlock() instanceof LeavesBlock`.
pub fn is_leaves_block(state: BlockState) -> bool {
    block_data(state).is_leaves_block
}

pub fn has_invisible_render_shape(state: BlockState) -> bool {
    block_data(state).render_shape_invisible.unwrap_or_else(|| {
        matches!(
            block_data(state).id,
            "air"
                | "cave_air"
                | "void_air"
                | "barrier"
                | "bubble_column"
                | "water"
                | "lava"
                | "light"
                | "end_portal"
                | "end_gateway"
                | "moving_piston"
                | "structure_void"
        )
    })
}

/// Java 26.2 FallingDust provider's FallingBlock.getDustColor overrides.
pub fn falling_block_dust_color(state: BlockState) -> Option<[u8; 3]> {
    let data = block_data(state);
    if let Some(rgb) = data.falling_dust_rgb {
        return Some([(rgb >> 16) as u8, (rgb >> 8) as u8, rgb as u8]);
    }
    let name = data.id;
    let rgb = match name {
        "sand" => 14_406_560u32,            // SandBlock(new ColorRGBA(14406560))
        "red_sand" => 11_098_145u32,        // SandBlock(new ColorRGBA(11098145))
        "gravel" => (-8_356_741i32) as u32, // ColoredFallingBlock(new ColorRGBA(...))
        "dragon_egg" => 0,                  // DragonEggBlock.getDustColor: -16777216
        "concrete_powder" | "anvil" | "chipped_anvil" | "damaged_anvil" => {
            return map_color_rgb(state);
        }
        _ => return None,
    };
    Some([(rgb >> 16) as u8, (rgb >> 8) as u8, rgb as u8])
}

/// Java MapColor RGB for common static and dye-derived states. The source
/// state dump currently does not include map colors; absent mappings are kept
/// explicit rather than substituted with a terrain tint.
pub fn map_color_rgb(state: BlockState) -> Option<[u8; 3]> {
    let data = block_data(state);
    if let Some(rgb) = data.map_color_rgb {
        return Some([(rgb >> 16) as u8, (rgb >> 8) as u8, rgb as u8]);
    }
    let name = data.id;
    let color = match name {
        "stone" | "andesite" | "polished_andesite" | "cobblestone" | "bedrock" | "iron_ore"
        | "gold_ore" | "coal_ore" | "copper_ore" | "emerald_ore" | "lapis_ore" => 0x707070,
        "granite" | "polished_granite" | "dirt" | "coarse_dirt" => 0x976D4D,
        "diorite" | "polished_diorite" | "quartz_block" | "quartz_bricks" => 0xFFFCF5,
        "grass_block" => 0x7FB238,
        "sand" => 0xF7E9A3,
        "red_sand" => 0xD87F33,
        "gravel" => 0x707070,
        "anvil" | "chipped_anvil" | "damaged_anvil" | "iron_block" => 0xA7A7A7,
        "dragon_egg" => 0x191919,
        "water" | "bubble_column" => 0x4040FF,
        "lava" => 0xFF0000,
        "snow_block" | "powder_snow" => 0xFFFFFF,
        "wool" | "white_wool" => 0xC7C7C7,
        _ => return dye_map_color(name.strip_suffix("_concrete_powder")?),
    };
    Some([(color >> 16) as u8, (color >> 8) as u8, color as u8])
}

fn dye_map_color(name: &str) -> Option<[u8; 3]> {
    let c = match name {
        "white" => 0xFFFFFF,
        "orange" => 0xD87F33,
        "magenta" => 0xB24CD8,
        "light_blue" => 0x6699D8,
        "yellow" => 0xE5E533,
        "lime" => 0x7FCC19,
        "pink" => 0xF27FA5,
        "gray" => 0x4C4C4C,
        "light_gray" => 0x999999,
        "cyan" => 0x4C7F99,
        "purple" => 0x7F3FB2,
        "blue" => 0x334CB2,
        "brown" => 0x664C33,
        "green" => 0x667F33,
        "red" => 0x993333,
        "black" => 0x191919,
        _ => return None,
    };
    Some([(c >> 16) as u8, (c >> 8) as u8, c as u8])
}

/// Vanilla `isAir`: includes cave and void air.
pub fn is_air(state: BlockState) -> bool {
    block_data(state).is_air
}

/// Whether the state's block collides with entities (vanilla `hasCollision`).
pub fn has_collision(state: BlockState) -> bool {
    block_data(state).collides
}

/// Vanilla base replaceable flag. Item/context checks belong to the placement
/// caller.
pub fn is_replaceable(state: BlockState) -> bool {
    block_data(state).replaceable
}

/// Java block type result used by `BucketItem.use`; `None` means this older
/// version table predates the generated interface-membership metadata.
pub fn liquid_block_container_type(state: BlockState) -> Option<bool> {
    block_data(state).liquid_block_container
}

/// Exact Java block type check used by `BucketItem.use` before checking whether
/// the current state accepts water.
#[cfg(test)]
pub fn is_liquid_block_container(state: BlockState) -> bool {
    liquid_block_container_type(state).unwrap_or(false)
}

/// Java `LiquidBlockContainer.canPlaceLiquid(player, ..., Fluids.WATER)` for
/// the native 26.2 simple-waterlogged blocks represented by registry state.
pub fn can_place_water(state: BlockState, creative: bool) -> bool {
    let data = block_data(state);
    // BarrierBlock is the only LiquidBlockContainer implementation whose
    // result depends on the caller; Java requires a creative Player.
    if data.id == "barrier" {
        return creative;
    }
    data.can_place_liquid_water.unwrap_or_else(|| {
        // Compatibility fallback for state tables without native call results.
        let properties = block_properties(state);
        properties.get("waterlogged") == Some("false") && properties.get("type") != Some("double")
    })
}

/// Java `BlockState.canBeReplaced(Fluids.WATER)`, including block overrides.
pub fn can_be_replaced_by_water(state: BlockState) -> bool {
    let data = block_data(state);
    data.can_be_replaced_by_water.unwrap_or_else(|| {
        // Legacy version tables predate this native per-state query.
        if matches!(data.id, "end_portal" | "end_gateway") {
            return false;
        }
        data.replaceable || !legacy_solid(state)
    })
}

fn legacy_solid(state: BlockState) -> bool {
    let data = block_data(state);
    if data.dynamic_shape {
        return false;
    }
    let Some(boxes) = data.shape.as_deref() else {
        return data.collides;
    };
    let Some(first) = boxes.first() else {
        return false;
    };
    let (mut min_x, mut min_y, mut min_z) = (first[0], first[1], first[2]);
    let (mut max_x, mut max_y, mut max_z) = (first[3], first[4], first[5]);
    for shape in &boxes[1..] {
        min_x = min_x.min(shape[0]);
        min_y = min_y.min(shape[1]);
        min_z = min_z.min(shape[2]);
        max_x = max_x.max(shape[3]);
        max_y = max_y.max(shape[4]);
        max_z = max_z.max(shape[5]);
    }
    let (x, y, z) = (max_x - min_x, max_y - min_y, max_z - min_z);
    (x + y + z) / 3.0 >= 0.7291666666666666 || y >= 1.0
}

/// Fluid `FlowingFluid.getFlow` uses this independently of entity collision.
pub fn blocks_motion(state: BlockState) -> bool {
    block_data(state).blocks_motion
}

/// Whether a horizontal face provides FULL support, as used by the falling-
/// fluid downward-flow bias. Soul sand's support shape is explicitly full;
/// other blocks use the existing baked boxes.
pub fn has_full_horizontal_sturdy_face(state: BlockState, dx: i32, dz: i32) -> bool {
    if !matches!((dx, dz), (1, 0) | (-1, 0) | (0, 1) | (0, -1)) {
        return false;
    }
    if block_id(state) == "soul_sand" {
        return true;
    }
    let full_cube = [0.0, 0.0, 0.0, 1.0, 1.0, 1.0];
    let boxes = block_data(state)
        .shape
        .as_deref()
        .unwrap_or(std::slice::from_ref(&full_cube));
    boxes.iter().any(|b| {
        if dx != 0 {
            b[if dx > 0 { 3 } else { 0 }] == if dx > 0 { 1.0 } else { 0.0 }
                && b[2] == 0.0
                && b[5] == 1.0
                && b[4] == 1.0
        } else {
            b[if dz > 0 { 5 } else { 2 }] == if dz > 0 { 1.0 } else { 0.0 }
                && b[0] == 0.0
                && b[3] == 1.0
                && b[4] == 1.0
        }
    })
}

pub fn fluid(state: BlockState) -> Fluid {
    block_data(state).fluid
}

/// Whether two states carry the same renderable fluid type. Vanilla's
/// FluidRenderer culls by fluid type; amount/source remain available for the
/// separate height/flow calculation. This is independent of block-shape
/// occlusion so waterlogged solids participate too.
pub fn same_fluid(a: Fluid, b: Fluid) -> bool {
    a.kind != FluidKind::Empty && a.kind == b.kind
}

pub(crate) fn block_shape(state: BlockState) -> Option<&'static [LocalBox]> {
    block_data(state).shape.as_deref()
}

/// Java 26.2 `PotentSulfurBlockEntity.canBeReachedByNoxiousGas` and
/// `isGeyserPassableBlock`, reduced to the collision/fluid data available here.
/// Missing world data fails closed rather than treating an unloaded chunk as
/// air.
pub fn noxious_gas_reachable(
    source: BlockPos,
    target: DVec3,
    mut block_at: impl FnMut(BlockPos) -> Option<BlockState>,
) -> bool {
    let target_pos = BlockPos::new(
        target.x.floor() as i32,
        target.y.floor() as i32,
        target.z.floor() as i32,
    );
    if target.distance_squared(DVec3::new(
        f64::from(source.x) + 0.5,
        f64::from(source.y) + 0.5,
        f64::from(source.z) + 0.5,
    )) > 9.0
    {
        return false;
    }
    let Some(target_state) = block_at(target_pos) else {
        return false;
    };
    if !noxious_gas_collision_empty(target_state, target_pos, Some(target_pos.y - 1)) {
        return false;
    }

    let below = DVec3::new(target.x, target.y - 1.0, target.z);
    let below_pos = BlockPos::new(
        below.x.floor() as i32,
        below.y.floor() as i32,
        below.z.floor() as i32,
    );
    let Some(water_state) = block_at(below_pos) else {
        return false;
    };
    let fluid = fluid(water_state);
    if fluid.kind != FluidKind::Water || fluid.amount != 8 {
        return false;
    }

    let start = DVec3::new(
        f64::from(source.x) + 0.5,
        f64::from(source.y) - 0.5,
        f64::from(source.z) + 0.5,
    );
    noxious_gas_line_clear(start, below, &mut block_at)
}

/// `isGeyserPassableBlock` uses a position context; the LOS clip uses the
/// empty context. Only scaffolding has a context-dependent collision shape in
/// the supported block-shape model.
pub fn noxious_gas_collision_empty(
    state: BlockState,
    pos: BlockPos,
    context_y: Option<i32>,
) -> bool {
    let id = block_id(state);
    if is_air(state) || id == "water" || id == "powder_snow" {
        return true;
    }
    if !has_collision(state) {
        return true;
    }
    if id == "scaffolding" {
        let Some(y) = context_y else { return true };
        let above_full = f64::from(y) > f64::from(pos.y) + 1.0 - 1.0e-5;
        if above_full {
            return false;
        }
        let above_below = f64::from(y) > f64::from(pos.y) - 1.0e-5;
        let props = block_properties(state);
        let distance = props
            .get("distance")
            .and_then(|v| v.parse::<u8>().ok())
            .unwrap_or(0);
        let bottom = props.get("bottom") == Some("true");
        return !(distance != 0 && bottom && above_below);
    }
    block_shape(state).is_some_and(|shape| shape.is_empty())
}

fn noxious_gas_line_clear(
    start: DVec3,
    end: DVec3,
    block_at: &mut impl FnMut(BlockPos) -> Option<BlockState>,
) -> bool {
    let min_x = start.x.min(end.x).floor() as i32;
    let max_x = start.x.max(end.x).floor() as i32;
    let min_y = start.y.min(end.y).floor() as i32;
    let max_y = start.y.max(end.y).floor() as i32;
    let min_z = start.z.min(end.z).floor() as i32;
    let max_z = start.z.max(end.z).floor() as i32;
    for x in min_x..=max_x {
        for y in min_y..=max_y {
            for z in min_z..=max_z {
                let pos = BlockPos::new(x, y, z);
                let Some(state) = block_at(pos) else {
                    return false;
                };
                if !noxious_gas_collision_empty(state, pos, None)
                    && block_shape(state)
                        .unwrap_or(&[[0.0, 0.0, 0.0, 1.0, 1.0, 1.0]])
                        .iter()
                        .any(|shape| segment_intersects_box(start, end, pos, *shape))
                {
                    return false;
                }
            }
        }
    }
    true
}

fn segment_intersects_box(start: DVec3, end: DVec3, pos: BlockPos, b: LocalBox) -> bool {
    let bounds = [
        (f64::from(pos.x) + b[0], f64::from(pos.x) + b[3]),
        (f64::from(pos.y) + b[1], f64::from(pos.y) + b[4]),
        (f64::from(pos.z) + b[2], f64::from(pos.z) + b[5]),
    ];
    let origin = [start.x, start.y, start.z];
    let delta = [end.x - start.x, end.y - start.y, end.z - start.z];
    let (mut enter, mut exit) = (0.0_f64, 1.0_f64);
    for axis in 0..3 {
        if delta[axis] == 0.0 {
            if origin[axis] < bounds[axis].0 || origin[axis] > bounds[axis].1 {
                return false;
            }
        } else {
            let a = (bounds[axis].0 - origin[axis]) / delta[axis];
            let b = (bounds[axis].1 - origin[axis]) / delta[axis];
            enter = enter.max(a.min(b));
            exit = exit.min(a.max(b));
            if enter > exit {
                return false;
            }
        }
    }
    exit >= 0.0 && enter <= 1.0
}

/// Outline shape for interaction raycasts (vanilla `getShape`), falling back to
/// the collision shape where the two agree. `None` is a full cube; an empty
/// slice is a block the pick ray passes through.
pub(crate) fn block_outline(state: BlockState) -> Option<&'static [LocalBox]> {
    let data = block_data(state);
    data.outline.as_deref().or(data.shape.as_deref())
}

/// Exact Java interface behavior obtained from the registered block instance;
/// `None` means the state's block does not implement `BonemealableBlock`.
pub fn bonemeal_particle_info(state: BlockState) -> Option<(BonemealParticleType, [i32; 3])> {
    let data = block_data(state);
    let kind = match data.bonemeal_type? {
        1 => BonemealParticleType::NeighborSpreader,
        2 => BonemealParticleType::Grower,
        _ => unreachable!("validated bonemeal type metadata"),
    };
    Some((kind, data.bonemeal_particle_offset))
}

/// Java `BlockState.getShape(level, pos).max(Y)` for generated 26.2 data.
/// Older tables fall back to the currently represented outline boxes.
pub fn outline_shape_max_y(state: BlockState) -> f64 {
    let data = block_data(state);
    data.shape_max_y_32nds.map_or_else(
        || {
            data.outline
                .as_deref()
                .or(data.shape.as_deref())
                .unwrap_or(&[[0.0, 0.0, 0.0, 1.0, 1.0, 1.0]])
                .iter()
                .map(|bounds| bounds[4])
                .fold(0.0, f64::max)
        },
        |height| {
            if height == 255 {
                f64::NEG_INFINITY
            } else {
                f64::from(height) / 32.0
            }
        },
    )
}

/// World-aware outline height query for event particle positions. Static state
/// shapes use Java's generated `getShape(...).max(Y)` metadata. Shulker boxes
/// are the registered dynamic outline shape whose height follows the existing
/// block-entity openness animation.
pub fn outline_shape_max_y_at(
    chunks: &crate::world::chunk::ChunkStore,
    pos: BlockPos,
    animations: &crate::world::block_entity_anim::BlockEntityAnimStore,
) -> f64 {
    let state = chunks.get_block_state(pos.x, pos.y, pos.z);
    let progress = animations
        .container(&pos)
        .map_or(0.0, |animation| animation.openness(1.0));
    dynamic_outline_shape_max_y(state, progress).unwrap_or_else(|| outline_shape_max_y(state))
}

fn dynamic_outline_shape_max_y(state: BlockState, progress: f32) -> Option<f64> {
    let id = block_id(state);
    if id != "shulker_box" && !id.ends_with("_shulker_box") {
        return None;
    }
    Some(if block_properties(state).get("facing") == Some("up") {
        1.0 + f64::from(progress) * 0.5
    } else {
        1.0
    })
}

/// Collision-shape fullness from Java's `BlockState.isCollisionShapeFullBlock`.
/// Dynamic shapes use the loaded world query entry point; the generated `h`
/// cache is Java's exact empty-context result for the state.
pub fn is_collision_shape_full_block(
    chunks: &crate::world::chunk::ChunkStore,
    pos: BlockPos,
) -> bool {
    let state = chunks.get_block_state(pos.x, pos.y, pos.z);
    let data = block_data(state);
    if data.dynamic_shape {
        // These vanilla dynamic-shape classes explicitly return false for this
        // predicate, independent of position.
        if matches!(data.id, "bamboo" | "pointed_dripstone" | "sulfur_spike") {
            return false;
        }
        if data.id == "moving_piston" {
            let Some(moving) = chunks.block_entities.get(&pos).and_then(|entity| {
                crate::world::block_entity::moving_block_render_details(&entity.nbt)
            }) else {
                return false;
            };
            return moving_piston_collision_is_full(&moving);
        }
    }
    collision_shape_is_full_block(state)
}

fn moving_piston_collision_is_full(moving: &crate::world::block_entity::MovingBlockRender) -> bool {
    !moving.source
        && moving.offset == glam::DVec3::ZERO
        && collision_shape_is_full_block(moving.state)
}

pub fn collision_shape_is_full_block(state: BlockState) -> bool {
    let data = block_data(state);
    data.collision_shape_full_block
        .unwrap_or_else(|| collision_shape_union_is_full(data))
}

fn collision_shape_union_is_full(data: &BlockData) -> bool {
    if !data.collides {
        return false;
    }
    let Some(boxes) = data.shape.as_deref() else {
        return true;
    };
    let mut occupied = [false; 16 * 16 * 16];
    for bounds in boxes {
        let cells = std::array::from_fn::<_, 3, _>(|axis| {
            let min = (bounds[axis] * 16.0).round() as i32;
            let max = (bounds[axis + 3] * 16.0).round() as i32;
            (min.clamp(0, 16), max.clamp(0, 16))
        });
        for y in cells[1].0..cells[1].1 {
            for z in cells[2].0..cells[2].1 {
                for x in cells[0].0..cells[0].1 {
                    occupied[(y * 16 * 16 + z * 16 + x) as usize] = true;
                }
            }
        }
    }
    occupied.into_iter().all(|cell| cell)
}

/// Baked light properties for a state (vanilla `BlockStateBase` light cache).
pub fn light_props(state: BlockState) -> LightProps {
    block_data(state).light
}

/// Vanilla `LightEngine.isEmptyShape`: the state needs no voxel-shape
/// occlusion tests (full opaque cubes qualify — their opacity handles them).
pub fn is_empty_shape(state: BlockState) -> bool {
    let light = block_data(state).light;
    !light.can_occlude || !light.use_shape_for_light_occlusion
}

/// Vanilla `LightEngine.shapeOccludes(from, to, dir)` reduced to face masks:
/// whether `from`'s face and `to`'s opposite face together cover the full
/// face. `face` is the vanilla `Direction` ordinal (DOWN, UP, NORTH, SOUTH,
/// WEST, EAST); opposites pair as `face ^ 1`. Empty-shape states contribute
/// an empty mask, so two shapeless neighbors never occlude.
pub fn shape_occludes(from: BlockState, to: BlockState, face: usize) -> bool {
    let mask = |state: BlockState, face: usize| {
        block_data(state)
            .light
            .face_occlusion
            .map(|masks| &masks[face])
    };
    let a = mask(from, face);
    let b = mask(to, face ^ 1);
    if a.is_none() && b.is_none() {
        return false;
    }
    (0..16).all(|v| (a.map_or(0, |m| m[v]) | b.map_or(0, |m| m[v])) == 0xFFFF)
}

/// The block's state matching the given property values (unlisted properties
/// take whatever the first match has); shared with the light-engine tests.
#[cfg(test)]
pub(crate) fn find_state(name: &str, props: &[(&str, &str)]) -> BlockState {
    all_states()
        .find(|(s, d)| {
            d.id == name
                && props
                    .iter()
                    .all(|&(k, v)| block_properties(*s).get(k) == Some(v))
        })
        .unwrap_or_else(|| panic!("no state {name} {props:?}"))
        .0
}

#[cfg(test)]
mod tests {
    use super::*;

    fn setup() {
        init("26.2");
    }

    #[test]
    fn water_replacement_uses_vanillas_final_per_state_query() {
        let _protocol = crate::world::block::test_protocol_guard();
        setup();
        for (name, expected) in [
            ("cobweb", false),
            ("oak_sign", false),
            ("ladder", true),
            ("end_rod", true),
            ("short_grass", true),
            ("stone", false),
            ("end_portal", false),
            ("end_gateway", false),
        ] {
            let state = default_state_of(name).unwrap();
            assert_eq!(
                block_data(state).can_be_replaced_by_water,
                Some(expected),
                "{name}"
            );
            assert_eq!(can_be_replaced_by_water(state), expected, "{name}");
        }
        let cobweb = default_state_of("cobweb").unwrap();
        assert!(is_replaceable(cobweb) || !legacy_solid(cobweb));
        assert!(!can_be_replaced_by_water(cobweb));
        let moving_piston = default_state_of("moving_piston").unwrap();
        assert!(!is_replaceable(moving_piston) && !legacy_solid(moving_piston));
        assert!(!can_be_replaced_by_water(moving_piston));
        let big_dripleaf = default_state_of("big_dripleaf").unwrap();
        assert!(!is_replaceable(big_dripleaf) && legacy_solid(big_dripleaf));
        assert!(can_be_replaced_by_water(big_dripleaf));
        for waterlogged in ["false", "true"] {
            let sign = find_state(
                "oak_sign",
                &[("rotation", "0"), ("waterlogged", waterlogged)],
            );
            assert!(!can_be_replaced_by_water(sign));
            assert!(
                can_place_water(sign, false),
                "SimpleWaterloggedBlock accepts water at both states"
            );
            let ladder = find_state(
                "ladder",
                &[("facing", "north"), ("waterlogged", waterlogged)],
            );
            assert!(is_liquid_block_container(ladder));
            assert!(can_be_replaced_by_water(ladder));
            assert!(can_place_water(ladder, false));
        }

        for name in ["seagrass", "kelp", "kelp_plant", "tall_seagrass"] {
            let state = default_state_of(name).unwrap();
            assert!(is_liquid_block_container(state), "{name}");
            assert!(
                block_properties(state).get("waterlogged").is_none(),
                "{name}"
            );
            assert!(!can_place_water(state, false), "{name}");
        }

        let double_slab = find_state("oak_slab", &[("type", "double"), ("waterlogged", "false")]);
        assert!(is_liquid_block_container(double_slab));
        assert!(!can_place_water(double_slab, false));
        let barrier = default_state_of("barrier").unwrap();
        assert!(is_liquid_block_container(barrier));
        assert!(!can_place_water(barrier, false));
        assert!(can_place_water(barrier, true));

        let wet_sign = find_state("oak_sign", &[("rotation", "0"), ("waterlogged", "true")]);
        assert!(is_liquid_block_container(wet_sign));
        assert!(!can_be_replaced_by_water(wet_sign));
        assert!(can_place_water(wet_sign, false));

        for waterlogged in ["false", "true"] {
            let state = find_state(
                "oak_stairs",
                &[
                    ("facing", "north"),
                    ("half", "bottom"),
                    ("shape", "straight"),
                    ("waterlogged", waterlogged),
                ],
            );
            assert_eq!(block_data(state).can_be_replaced_by_water, Some(false));
            assert!(is_liquid_block_container(state));
            assert!(can_place_water(state, false));
            assert!(!can_be_replaced_by_water(state));
        }
    }

    #[test]
    fn block_tag_registry_ids_resolve_by_source_protocol_identity_once() {
        let _protocol = crate::world::block::test_protocol_guard();
        setup();
        assert_eq!(
            block_name_for_registry_id(763, 94).as_deref(),
            Some("glass")
        );
        let glass =
            default_state_of(block_name_for_registry_id(763, 94).unwrap().as_str()).unwrap();
        assert_eq!(block_id(glass), "glass");
        assert_eq!(
            block_name_for_registry_id(776, 101).as_deref(),
            Some("glass")
        );
        assert_eq!(
            block_name_for_registry_id(763, 94),
            block_name_for_registry_id(776, 101)
        );
    }

    #[test]
    fn noxious_gas_reach_uses_java_collision_fluid_and_loaded_world_rules() {
        let _protocol = crate::world::block::test_protocol_guard();
        setup();
        let source = BlockPos::new(0, 66, 0);
        let target = DVec3::new(2.5, 66.25, 0.5);
        let water = find_state("water", &[("level", "0")]);
        let stone = find_state("stone", &[]);
        let mut states = HashMap::from([(BlockPos::new(2, 65, 0), water)]);
        let at = |pos: BlockPos, states: &HashMap<BlockPos, BlockState>| {
            Some(*states.get(&pos).unwrap_or(&BlockState::AIR))
        };
        assert!(noxious_gas_reachable(source, target, |p| at(p, &states)));

        states.insert(BlockPos::new(1, 65, 0), stone);
        assert!(!noxious_gas_reachable(source, target, |p| at(p, &states)));
        states.remove(&BlockPos::new(1, 65, 0));
        assert!(!noxious_gas_reachable(source, target, |p| {
            (p != BlockPos::new(1, 65, 0)).then(|| *states.get(&p).unwrap_or(&BlockState::AIR))
        }));

        let bottom_slab = find_state("oak_slab", &[("type", "bottom"), ("waterlogged", "false")]);
        let waterlogged_slab =
            find_state("oak_slab", &[("type", "bottom"), ("waterlogged", "true")]);
        let stairs = find_state(
            "oak_stairs",
            &[
                ("facing", "north"),
                ("half", "bottom"),
                ("shape", "straight"),
                ("waterlogged", "false"),
            ],
        );
        assert!(!noxious_gas_collision_empty(
            bottom_slab,
            BlockPos::new(1, 65, 0),
            None
        ));
        assert!(!noxious_gas_collision_empty(
            stairs,
            BlockPos::new(1, 65, 0),
            None
        ));
        assert!(!noxious_gas_collision_empty(
            waterlogged_slab,
            BlockPos::new(1, 65, 0),
            None
        ));
        states.insert(BlockPos::new(2, 65, 0), waterlogged_slab);
        assert!(!noxious_gas_reachable(source, target, |p| at(p, &states)));

        assert!(!noxious_gas_reachable(source, target, |_| None));
        assert!(!noxious_gas_collision_empty(
            stone,
            BlockPos::new(1, 65, 0),
            None
        ));
    }

    #[test]
    fn vanilla_26_2_block_offsets_match_xz_seed_contract_and_version_gate() {
        let _protocol = crate::world::block::test_protocol_guard();
        setup();
        let plant = find_state("dandelion", &[]);
        let same_column = block_offset(plant, BlockPos::new(-123, -40, 77));
        assert_eq!(
            same_column,
            block_offset(plant, BlockPos::new(-123, 900, 77))
        );
        assert!((same_column.x - -0.21666666492819786).abs() < 1.0e-12);
        assert!((same_column.z - -0.11666665971279144).abs() < 1.0e-12);
        assert!(same_column.x.abs() <= 0.25 && same_column.z.abs() <= 0.25);
        let spike = find_state(
            "pointed_dripstone",
            &[
                ("thickness", "base"),
                ("vertical_direction", "up"),
                ("waterlogged", "false"),
            ],
        );
        let spike_offset = block_offset(spike, BlockPos::new(i32::MIN, 0, i32::MAX));
        assert!(spike_offset.x.abs() <= 0.125 && spike_offset.z.abs() <= 0.125);
        assert_eq!(
            block_offset(find_state("stone", &[]), BlockPos::new(-1, 0, -1)),
            DVec3::ZERO
        );
        init("1.21.11");
        let old_plant = find_state("dandelion", &[]);
        assert_eq!(
            block_offset(old_plant, BlockPos::new(17, 0, -21)),
            DVec3::ZERO
        );
    }

    #[test]
    fn shape_dictionary_accepts_finite_ordered_boxes_outside_unit_bounds() {
        validate_shape_boxes(&[vec![[-0.25, 0.0, 0.0, 1.0, 1.5, 1.0]]]);
    }

    #[test]
    fn shape_dictionary_rejects_inverted_bounds() {
        let result = std::panic::catch_unwind(|| {
            validate_shape_boxes(&[vec![[1.0, 0.0, 0.0, 0.0, 1.0, 1.0]]]);
        });
        assert!(result.is_err());
    }

    #[test]
    fn shape_dictionary_rejects_non_finite_coordinates() {
        for coordinate in [f64::NAN, f64::INFINITY, f64::NEG_INFINITY] {
            let result = std::panic::catch_unwind(|| {
                validate_shape_boxes(&[vec![[0.0, 0.0, 0.0, coordinate, 1.0, 1.0]]]);
            });
            assert!(result.is_err(), "accepted {coordinate}");
        }
    }

    #[test]
    fn chest_states_decode() {
        let _protocol = crate::world::block::test_protocol_guard();
        setup();
        // Oracle from reference/26.2/generated/reports/blocks.json:
        // chest[type=single,facing=south,waterlogged=false] is id 3994 — the
        // state that previously decoded as facing=east under azalea's stale
        // 26.1 tables.
        let state = try_state(3994).unwrap();
        assert_eq!(block_id(state), "chest");
        let props = block_properties(state);
        assert_eq!(props.get("facing"), Some("south"));
        assert_eq!(props.get("type"), Some("single"));
        assert_eq!(props.get("waterlogged"), Some("false"));
    }

    #[test]
    fn default_states_use_registered_default_not_first_state() {
        let _protocol = crate::world::block::test_protocol_guard();
        setup();
        for name in ["oak_log", "oak_slab", "oak_sign", "chest"] {
            let file: BlockFile = serde_json::from_str(BLOCK_DATA[NATIVE_SLOT].blocks).unwrap();
            let entry = file.blocks.iter().find(|entry| entry.name == name).unwrap();
            assert_ne!(entry.first_id, entry.default_id, "{name}");
            assert_eq!(u32::from(default_state_of(name).unwrap()), entry.default_id);
        }
        assert!(default_state_of("missing_block").is_none());
    }

    #[test]
    fn new_26_2_blocks_resolve() {
        let _protocol = crate::world::block::test_protocol_guard();
        setup();
        assert!(all_states().any(|(_, d)| d.id == "copper_chest"));
        assert!(try_state(u32::MAX).is_none());
        let count = table().len() as u32;
        assert!(try_state(count).is_none());
        assert!(try_state(count - 1).is_some());
    }

    #[test]
    fn redstone_wire_colors() {
        let _protocol = crate::world::block::test_protocol_guard();
        setup();
        let unpowered = find_state("redstone_wire", &[("power", "0")]);
        assert_eq!(redstone_wire_rgb(unpowered), [0.3, 0.0, 0.0]);
        let full = redstone_wire_rgb(find_state("redstone_wire", &[("power", "15")]));
        for (got, want) in full.iter().zip([1.0, 0.2, 0.0]) {
            assert!((got - want).abs() < 1e-6, "{full:?}");
        }
    }

    #[test]
    fn stem_colors_follow_vanilla_age_formula() {
        let _protocol = crate::world::block::test_protocol_guard();
        setup();
        for age in 0..=7 {
            let state = find_state("pumpkin_stem", &[("age", &age.to_string())]);
            let expected = [
                age as f32 * 32.0 / 255.0,
                (255.0 - age as f32 * 8.0) / 255.0,
                age as f32 * 4.0 / 255.0,
            ];
            for (got, want) in stem_rgb(state).into_iter().zip(expected) {
                assert!((got - want).abs() < 1e-6, "age={age}: {got} != {want}");
            }
        }
    }

    #[test]
    fn fluid_states() {
        let _protocol = crate::world::block::test_protocol_guard();
        setup();
        let (still, _) = all_states()
            .find(|(s, d)| d.id == "water" && block_properties(*s).get("level") == Some("0"))
            .unwrap();
        let f = fluid(still);
        assert_eq!(f.kind, FluidKind::Water);
        assert_eq!(f.amount, 8);
        assert!(!f.falling);

        let (falling, _) = all_states()
            .find(|(s, d)| d.id == "water" && block_properties(*s).get("level") == Some("9"))
            .unwrap();
        assert!(fluid(falling).falling);

        let (logged, _) = all_states()
            .find(|(s, d)| {
                d.id == "oak_stairs" && block_properties(*s).get("waterlogged") == Some("true")
            })
            .unwrap();
        assert_eq!(fluid(logged).kind, FluidKind::Water);
        assert_eq!(fluid(logged).amount, 8);

        assert_eq!(fluid(BlockState::AIR).kind, FluidKind::Empty);
        assert!(same_fluid(f, fluid(logged)));
        assert!(same_fluid(f, fluid(falling)));
        assert!(!same_fluid(f, fluid(BlockState::AIR)));
    }

    #[test]
    fn collision_flags() {
        let _protocol = crate::world::block::test_protocol_guard();
        setup();
        // Oracles from reference/26.2/decompiled Blocks.java noCollision sites.
        assert!(!has_collision(BlockState::AIR));
        assert!(!has_collision(find_state("torch", &[])));
        assert!(!has_collision(find_state("water", &[("level", "0")])));
        assert!(!has_collision(find_state("oak_button", &[])));
        assert!(has_collision(find_state("stone", &[])));
        assert!(has_collision(find_state("oak_fence", &[])));
    }

    #[test]
    fn light_emission_values() {
        let _protocol = crate::world::block::test_protocol_guard();
        setup();
        // Oracles from reference/26.2/decompiled Blocks.java lightLevel sites.
        assert_eq!(light_props(find_state("torch", &[])).emission, 14);
        assert_eq!(light_props(find_state("glowstone", &[])).emission, 15);
        assert_eq!(
            light_props(find_state("redstone_lamp", &[("lit", "true")])).emission,
            15
        );
        assert_eq!(
            light_props(find_state("redstone_lamp", &[("lit", "false")])).emission,
            0
        );
        assert_eq!(
            light_props(find_state(
                "sea_pickle",
                &[("pickles", "3"), ("waterlogged", "true")]
            ))
            .emission,
            12
        );
        assert_eq!(
            light_props(find_state(
                "sea_pickle",
                &[("pickles", "3"), ("waterlogged", "false")]
            ))
            .emission,
            0
        );
        assert_eq!(
            light_props(find_state("cave_vines", &[("berries", "true")])).emission,
            14
        );
        assert_eq!(
            light_props(find_state("cave_vines", &[("berries", "false")])).emission,
            0
        );
        assert_eq!(
            light_props(find_state("light", &[("level", "7")])).emission,
            7
        );
    }

    #[test]
    fn light_dampening_values() {
        let _protocol = crate::world::block::test_protocol_guard();
        setup();
        let stone = light_props(find_state("stone", &[]));
        assert_eq!(stone.dampening, 15);
        assert!(stone.can_occlude);
        assert!(!stone.use_shape_for_light_occlusion);
        assert!(is_empty_shape(find_state("stone", &[])));

        assert_eq!(
            light_props(find_state("water", &[("level", "0")])).dampening,
            1
        );
        assert_eq!(light_props(find_state("oak_leaves", &[])).dampening, 1);
        let glass = light_props(find_state("glass", &[]));
        assert_eq!(glass.dampening, 0);
        assert!(glass.propagates_skylight_down);
        assert_eq!(light_props(BlockState::AIR).dampening, 0);
    }

    #[test]
    fn slab_face_occlusion() {
        let _protocol = crate::world::block::test_protocol_guard();
        setup();
        let top = find_state("oak_slab", &[("type", "top"), ("waterlogged", "false")]);
        let bottom = find_state("oak_slab", &[("type", "bottom"), ("waterlogged", "false")]);
        let double = find_state("oak_slab", &[("type", "double")]);
        let stone = find_state("stone", &[]);

        assert!(!is_empty_shape(top));
        assert!(!is_empty_shape(bottom));
        // Double slabs are solid-render full cubes: no shape tests needed.
        assert!(is_empty_shape(double));

        // Vanilla Direction ordinals: DOWN=0, UP=1.
        const DOWN: usize = 0;
        const UP: usize = 1;
        // A top slab's UP face is full; a bottom slab's DOWN face is full.
        assert!(shape_occludes(top, stone, UP));
        assert!(shape_occludes(bottom, stone, DOWN));
        // The open halves don't occlude.
        assert!(!shape_occludes(top, stone, DOWN));
        assert!(!shape_occludes(bottom, stone, UP));
        // Top slab above a bottom slab: neither shape touches the seam plane,
        // so both face slices are empty and the seam stays open.
        assert!(!shape_occludes(top, bottom, DOWN));
        const NORTH: usize = 2;
        // Side faces of two aligned bottom slabs cover only the lower half.
        assert!(!shape_occludes(bottom, bottom, NORTH));
    }

    /// Oracles from reference/26.2/decompiled: `SnowLayerBlock` is the only
    /// shape here whose `getShape` and `getCollisionShape` disagree, and
    /// `LiquidBlock`/`BubbleColumnBlock` return `Shapes.empty()`.
    #[test]
    fn outline_shapes() {
        let _protocol = crate::world::block::test_protocol_guard();
        setup();

        // One snow layer is 2/16 tall to look at but has no collision at all.
        let thin = find_state("snow", &[("layers", "1")]);
        assert_eq!(block_shape(thin), Some(&[][..]));
        assert_eq!(
            block_outline(thin),
            Some(&[[0.0, 0.0, 0.0, 1.0, 2.0 / 16.0, 1.0]][..])
        );
        // Eight layers fill the cell visually but collide one layer short.
        let full = find_state("snow", &[("layers", "8")]);
        assert_eq!(
            block_shape(full),
            Some(&[[0.0, 0.0, 0.0, 1.0, 14.0 / 16.0, 1.0]][..])
        );
        assert_eq!(
            block_outline(full),
            Some(&[[0.0, 0.0, 0.0, 1.0, 1.0, 1.0]][..])
        );

        // Fluids are clipped through, not targeted.
        for id in ["water", "lava"] {
            assert_eq!(
                block_outline(find_state(id, &[("level", "0")])),
                Some(&[][..])
            );
        }
        assert_eq!(
            block_outline(find_state("bubble_column", &[])),
            Some(&[][..])
        );

        // Everywhere else the collision shape doubles as the outline.
        let slab = find_state("oak_slab", &[("type", "bottom"), ("waterlogged", "false")]);
        assert_eq!(block_outline(slab), block_shape(slab));
        assert_eq!(block_outline(find_state("stone", &[])), None);
    }

    /// Builds every embedded table so the block/light cross-checks fire for
    /// all versions, not just the one `setup` activates.
    #[test]
    fn all_tables_build() {
        for data in BLOCK_DATA {
            build_table(data);
        }
    }

    /// Every block name in every embedded version table has an entry in the
    /// shared behavior and sound tables (a missing one would silently fall
    /// back to instant-break defaults and stone sounds), and every table key
    /// names a block in some embedded version (an orphan is a typo'd or
    /// stale entry — the defect class the legacy crop sound keys were).
    #[test]
    fn shared_tables_cover_all_versions() {
        let behaviors = load_behaviors();
        let mut known = HashSet::new();
        for data in BLOCK_DATA {
            let file: BlockFile = serde_json::from_str(data.blocks).unwrap();
            for block in &file.blocks {
                assert!(
                    behaviors.contains_key(&block.name),
                    "no behavior entry for '{}' ({})",
                    block.name,
                    file.version
                );
                assert!(
                    sound::BLOCK_SOUNDS.contains_key(&block.name),
                    "no sound entry for '{}' ({})",
                    block.name,
                    file.version
                );
                known.insert(block.name.clone());
            }
        }
        for key in behaviors.keys() {
            assert!(known.contains(key), "orphaned behavior entry '{key}'");
        }
        for key in sound::BLOCK_SOUNDS.keys() {
            assert!(known.contains(key), "orphaned sound entry '{key}'");
        }
    }

    /// Every launchable version has a block table (its own or a shared one);
    /// `prewarm_protocol` would otherwise fall back to 26.2's silently.
    #[test]
    fn block_data_covers_versions() {
        for v in pomme_protocol::version::VERSIONS {
            assert!(block_data_slot(v.protocol).is_some(), "{}", v.name);
        }
    }

    #[test]
    fn native_slot() {
        let native = pomme_protocol::version::NATIVE.protocol;
        assert_eq!(block_data_slot(native), Some(NATIVE_SLOT));
    }

    #[test]
    fn particle_filters_match_java_26_2_special_blocks() {
        let _protocol = crate::world::block::test_protocol_guard();
        setup();
        let state = |name| first_state_of(name).unwrap();
        assert!(!should_spawn_terrain_particles(state("barrier")));
        assert!(!should_spawn_terrain_particles(state("structure_void")));
        assert!(should_spawn_terrain_particles(state("stone")));
        assert!(has_invisible_render_shape(state("bubble_column")));
        assert!(has_invisible_render_shape(state("water")));
        assert!(has_invisible_render_shape(state("moving_piston")));
        assert!(!has_invisible_render_shape(state("stone")));
    }

    #[test]
    fn java_solid_render_metadata_distinguishes_non_full_renderable_states() {
        let _protocol = crate::world::block::test_protocol_guard();
        setup();
        assert_eq!(
            is_solid_render(first_state_of("stone").unwrap()),
            Some(true)
        );
        assert_eq!(
            is_solid_render(first_state_of("glass").unwrap()),
            Some(false)
        );
        assert_eq!(
            is_solid_render(first_state_of("oak_slab").unwrap()),
            Some(false)
        );
    }

    #[test]
    fn java_bonemeal_class_type_and_particle_pos_are_generated_from_block_instances() {
        let _protocol = crate::world::block::test_protocol_guard();
        setup();
        let info = |name| bonemeal_particle_info(first_state_of(name).unwrap());
        assert_eq!(
            info("grass_block"),
            Some((BonemealParticleType::NeighborSpreader, [0, 1, 0]))
        );
        assert_eq!(
            info("crimson_nylium"),
            Some((BonemealParticleType::NeighborSpreader, [0, 1, 0]))
        );
        assert_eq!(
            info("oak_sapling"),
            Some((BonemealParticleType::Grower, [0, 0, 0]))
        );
        assert_eq!(
            info("rooted_dirt"),
            Some((BonemealParticleType::Grower, [0, -1, 0]))
        );
        assert_eq!(
            info("mangrove_leaves"),
            Some((BonemealParticleType::Grower, [0, -1, 0]))
        );
        assert_eq!(info("water"), None);
        let counts = all_states().fold([0usize; 3], |mut counts, (_, data)| {
            counts[data.bonemeal_type.unwrap_or(0) as usize] += 1;
            counts
        });
        assert_eq!(counts, [31_645, 7, 714]);
    }

    #[test]
    fn java_collision_fullness_and_outline_height_use_shape_metadata() {
        let _protocol = crate::world::block::test_protocol_guard();
        setup();
        let stone = find_state("stone", &[]);
        let slab = find_state("oak_slab", &[("type", "bottom"), ("waterlogged", "false")]);
        let stairs = find_state(
            "oak_stairs",
            &[
                ("facing", "north"),
                ("half", "bottom"),
                ("shape", "straight"),
                ("waterlogged", "false"),
            ],
        );
        assert!(collision_shape_is_full_block(stone));
        assert!(!collision_shape_is_full_block(slab));
        assert!(!collision_shape_is_full_block(stairs));
        let stationary_moving = crate::world::block_entity::MovingBlockRender {
            state: stone,
            offset: glam::DVec3::ZERO,
            source: false,
            extending: true,
            progress: 1.0,
            direction: glam::DVec3::X,
        };
        assert!(moving_piston_collision_is_full(&stationary_moving));
        let translated_moving = crate::world::block_entity::MovingBlockRender {
            offset: glam::DVec3::X * 0.5,
            ..stationary_moving
        };
        assert!(!moving_piston_collision_is_full(&translated_moving));
        let source_piston = crate::world::block_entity::MovingBlockRender {
            source: true,
            ..stationary_moving
        };
        assert!(!moving_piston_collision_is_full(&source_piston));
        let mut chunks = crate::world::chunk::ChunkStore::new(2);
        let mut chunk = azalea_world::chunk::Chunk::default();
        chunk.sections = vec![Default::default(); chunks.section_count() as usize].into();
        let column = BlockPos::new(0, 0, 0);
        chunks.load_decoded_chunk(
            azalea_core::position::ChunkPos::new(column.x, column.z),
            chunk,
        );
        let pos = BlockPos::new(2, 64, 2);
        chunks.set_block_state(
            pos.x,
            pos.y,
            pos.z,
            first_state_of("moving_piston").unwrap(),
        );
        let moving_entity = |progress: f32, source: bool| {
            use simdnbt::owned::NbtTag;
            let mut moved = simdnbt::owned::NbtCompound::new();
            moved.insert("Name", "minecraft:stone");
            let mut nbt = simdnbt::owned::NbtCompound::new();
            nbt.insert("blockState", NbtTag::Compound(moved));
            nbt.insert("progress", NbtTag::Float(progress));
            nbt.insert("extending", NbtTag::Byte(1));
            nbt.insert("source", NbtTag::Byte(i8::from(source)));
            nbt.insert("facing", "north");
            nbt
        };
        chunks.block_entities.insert(
            pos,
            crate::world::block_entity::StoredBlockEntity::new(
                azalea_registry::builtin::BlockEntityKind::Piston,
                moving_entity(1.0, false),
            ),
        );
        assert!(is_collision_shape_full_block(&chunks, pos));
        chunks
            .block_entities
            .get_mut(&pos)
            .unwrap()
            .update_nbt(moving_entity(0.5, false));
        assert!(!is_collision_shape_full_block(&chunks, pos));
        chunks
            .block_entities
            .get_mut(&pos)
            .unwrap()
            .update_nbt(moving_entity(1.0, true));
        assert!(!is_collision_shape_full_block(&chunks, pos));
        let stairs_shape = crate::physics::block_shape::partial_shape(stairs).unwrap();
        for axis in 0..3 {
            assert_eq!(
                stairs_shape
                    .iter()
                    .map(|b| b[axis])
                    .fold(f64::INFINITY, f64::min),
                0.0
            );
            assert_eq!(
                stairs_shape
                    .iter()
                    .map(|b| b[axis + 3])
                    .fold(f64::NEG_INFINITY, f64::max),
                1.0
            );
        }
        assert_eq!(outline_shape_max_y(stone), 1.0);
        assert_eq!(outline_shape_max_y(find_state("oak_sapling", &[])), 0.75);
        assert_eq!(
            outline_shape_max_y(find_state("water", &[("level", "0")])),
            f64::NEG_INFINITY
        );
    }

    #[test]
    fn shulker_outline_max_y_tracks_world_owned_opening_state() {
        let _protocol = crate::world::block::test_protocol_guard();
        setup();
        let up = find_state("white_shulker_box", &[("facing", "up")]);
        let north = find_state("white_shulker_box", &[("facing", "north")]);
        assert_eq!(dynamic_outline_shape_max_y(up, 0.0), Some(1.0));
        assert_eq!(dynamic_outline_shape_max_y(up, 0.5), Some(1.25));
        assert_eq!(dynamic_outline_shape_max_y(up, 1.0), Some(1.5));
        assert_eq!(dynamic_outline_shape_max_y(north, 1.0), Some(1.0));
        assert_eq!(
            dynamic_outline_shape_max_y(find_state("stone", &[]), 1.0),
            None
        );
    }

    #[test]
    fn representative_java_falling_dust_colors() {
        let _protocol = crate::world::block::test_protocol_guard();
        setup();
        let state = |name| first_state_of(name).unwrap();
        assert_eq!(
            falling_block_dust_color(state("sand")),
            Some([219, 211, 160])
        );
        assert_eq!(
            falling_block_dust_color(state("red_sand")),
            Some([169, 88, 33])
        );
        assert_eq!(
            falling_block_dust_color(state("gravel")),
            Some([128, 124, 123])
        );
        assert_eq!(
            falling_block_dust_color(state("dragon_egg")),
            Some([0, 0, 0])
        );
        assert_eq!(
            falling_block_dust_color(state("anvil")),
            Some([167, 167, 167])
        );
        assert_eq!(
            falling_block_dust_color(state("white_concrete_powder")),
            Some([255; 3])
        );
        assert_eq!(map_color_rgb(state("stone")), Some([112; 3]));
        assert_eq!(
            map_color_rgb(state("orange_concrete_powder")),
            Some([216, 127, 51])
        );
    }
}
