pub mod model;
pub mod registry;
pub mod sound;

use std::collections::{HashMap, HashSet};
use std::sync::OnceLock;

use azalea_block::BlockState;

use crate::physics::block_shape::{LocalBox, compute_outline, compute_shape};

/// Compact per-state property map: `(key, value)` pairs sorted by key. States
/// have at most ~10 properties, so binary search on a boxed slice beats a
/// `HashMap` in both footprint and lookup cost.
pub struct PropMap(Box<[(&'static str, &'static str)]>);

impl PropMap {
    fn from_pairs(mut pairs: Vec<(&'static str, &'static str)>) -> Self {
        pairs.sort_unstable_by_key(|&(k, _)| k);
        Self(pairs.into_boxed_slice())
    }

    pub fn get(&self, key: &str) -> Option<&'static str> {
        self.0
            .binary_search_by_key(&key, |&(k, _)| k)
            .ok()
            .map(|i| self.0[i].1)
    }

    pub fn entries(&self) -> impl Iterator<Item = (&'static str, &'static str)> + '_ {
        self.0.iter().copied()
    }
}

/// The two behavior fields the client reads (from vanilla `BlockBehaviour`).
#[derive(Clone, Copy)]
pub struct BlockBehavior {
    pub destroy_time: f32,
    pub requires_correct_tool_for_drops: bool,
}

const DEFAULT_BEHAVIOR: BlockBehavior = BlockBehavior {
    destroy_time: 0.0,
    requires_correct_tool_for_drops: false,
};

/// A face-occlusion shape projected onto the face plane as a 16x16 bit grid;
/// `mask[v]` holds row `v`'s bits. Generated by `just stategen`.
pub type FaceMask = [u16; 16];

/// Per-state light properties (vanilla `BlockBehaviour.BlockStateBase`'s
/// baked light cache), loaded from the per-version table generated by
/// `tools/stategen` running vanilla's own code.
#[derive(Clone, Copy)]
pub struct LightProps {
    pub emission: u8,
    pub dampening: u8,
    /// Unconsumed at runtime (vanilla only folds it into `dampening` at
    /// bake time); carried for parity with the vanilla property set.
    #[allow(dead_code)]
    pub propagates_skylight_down: bool,
    pub can_occlude: bool,
    pub use_shape_for_light_occlusion: bool,
    /// Per-face occlusion masks in vanilla `Direction` ordinal order (DOWN,
    /// UP, NORTH, SOUTH, WEST, EAST); `Some` exactly when `can_occlude &&
    /// use_shape_for_light_occlusion`.
    pub face_occlusion: Option<&'static [FaceMask; 6]>,
}

/// Unknown states occlude fully, matching vanilla's bedrock fallback for
/// out-of-range light-engine reads.
const BEDROCK_LIGHT: LightProps = LightProps {
    emission: 0,
    dampening: 15,
    propagates_skylight_down: false,
    can_occlude: true,
    use_shape_for_light_occlusion: false,
    face_occlusion: None,
};

#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum FluidKind {
    Empty,
    Water,
    Lava,
}

/// Fluid content of a block state, matching vanilla `FluidState`: sources and
/// waterlogged blocks are amount 8; flowing fluid is `8 - level`; falling
/// fluid (level >= 8) renders/behaves as a full column.
#[derive(Clone, Copy)]
pub struct Fluid {
    pub kind: FluidKind,
    pub amount: u8,
    /// Not consumed yet; kept for vanilla parity (falling columns behave as
    /// full sources in flow/height logic).
    #[allow(dead_code)]
    pub falling: bool,
}

const NO_FLUID: Fluid = Fluid {
    kind: FluidKind::Empty,
    amount: 0,
    falling: false,
};

const FULL_WATER: Fluid = Fluid {
    kind: FluidKind::Water,
    amount: 8,
    falling: false,
};

impl Fluid {
    pub fn height(&self) -> f32 {
        self.amount as f32 / 9.0
    }

    pub fn is_source(&self) -> bool {
        self.kind != FluidKind::Empty && self.amount == 8 && !self.falling
    }
}

/// Per-state block data loaded from the per-version table generated by
/// `tools/blockgen` from Mojang's data-generator report. Hot paths (meshing
/// classifies and textures every block) index this directly.
struct BlockData {
    id: &'static str,
    properties: PropMap,
    behavior: BlockBehavior,
    /// Collision shape; see `block_shape::partial_shape` for the encoding.
    shape: Option<Box<[LocalBox]>>,
    /// Outline shape (vanilla `getShape`) where it differs from `shape`; `None`
    /// means the two agree and the collision shape doubles as the outline.
    outline: Option<Box<[LocalBox]>>,
    is_air: bool,
    /// Vanilla `hasCollision` (`BlockBehaviour.Properties.noCollision()`).
    collides: bool,
    fluid: Fluid,
    light: LightProps,
}

#[derive(serde::Deserialize)]
struct BlockFile {
    version: String,
    state_count: u32,
    blocks: Vec<BlockEntry>,
}

// The data files also carry a `default_id` per block; nothing client-side
// consumes it yet, so serde skips it.
#[derive(serde::Deserialize)]
struct BlockEntry {
    name: String,
    first_id: u32,
    /// `(key, values)` in state-enumeration order; the last property varies
    /// fastest across consecutive state ids.
    #[serde(default)]
    props: Vec<(String, Vec<String>)>,
}

#[derive(serde::Deserialize)]
struct BehaviorEntry {
    destroy_time: f32,
    requires_correct_tool: bool,
}

#[derive(serde::Deserialize)]
struct StateFile {
    version: String,
    state_count: u32,
    /// Deduped face masks as 64-hex-char strings (16 rows of 4 chars).
    masks: Vec<String>,
    blocks: Vec<StateEntry>,
}

/// Per-block fields; each is a scalar when uniform across the block's
/// states, else one value per state. `f` is 6 mask-dictionary indices —
/// a single tuple when uniform, else a per-state list of tuple-or-null.
#[derive(serde::Deserialize)]
struct StateEntry {
    name: String,
    e: ScalarOrPerState,
    d: ScalarOrPerState,
    p: ScalarOrPerState,
    o: ScalarOrPerState,
    u: ScalarOrPerState,
    /// `hasCollision`; block-level in vanilla, so always a scalar.
    c: u8,
    #[serde(default)]
    f: Option<serde_json::Value>,
}

#[derive(serde::Deserialize)]
#[serde(untagged)]
enum ScalarOrPerState {
    One(u8),
    Many(Vec<u8>),
}

impl ScalarOrPerState {
    fn get(&self, offset: usize) -> u8 {
        match self {
            Self::One(v) => *v,
            Self::Many(vs) => vs[offset],
        }
    }
}

/// One version's embedded block tables. `blocks` is the state layout (ids and
/// properties from the data-generator report); `state` (`just stategen`)
/// holds the per-state values vanilla bakes at runtime, dumped by running its
/// own code.
struct EmbeddedBlocks {
    protocol: i32,
    blocks: &'static str,
    state: &'static str,
}

/// The `blocks-<v>.json` / `state-<v>.json` pair for version `v`, keyed by
/// its protocol (checked against the file in [`build_table`]).
macro_rules! embedded_blocks {
    ($protocol:expr, $version:literal) => {
        EmbeddedBlocks {
            protocol: $protocol,
            blocks: include_str!(concat!("data/blocks-", $version, ".json")),
            state: include_str!(concat!("data/state-", $version, ".json")),
        }
    };
}

/// Per-protocol block-state data, the native version at [`NATIVE_SLOT`].
const BLOCK_DATA: &[EmbeddedBlocks] = &[
    embedded_blocks!(pomme_protocol::version::NATIVE.protocol, "26.2"),
    embedded_blocks!(777, "26.3"),
    embedded_blocks!(775, "26.1"),
    embedded_blocks!(774, "1.21.11"),
    embedded_blocks!(773, "1.21.10"),
    embedded_blocks!(772, "1.21.8"),
    embedded_blocks!(770, "1.21.5"),
    embedded_blocks!(769, "1.21.4"),
    embedded_blocks!(768, "1.21.3"),
    embedded_blocks!(767, "1.21.1"),
    embedded_blocks!(765, "1.20.4"),
    embedded_blocks!(764, "1.20.2"),
    embedded_blocks!(763, "1.20.1"),
];

/// Protocols whose block set is identical to a newer embedded version's (no
/// blocks added between them); they share that version's slot instead of
/// building a second copy of the same table. The slot also serves the state
/// table, so an alias requires the two versions' `generated/state.json`
/// dumps to be identical as well, not just the block list.
const SHARED_BLOCK_DATA: &[(i32, i32)] = &[
    // 1.21.7 added no blocks.
    (771, 772),
    // 1.21's trial-chamber blocks already existed in 1.20.6.
    (766, 767),
];

/// One lazily-built table per embedded data file; `ACTIVE_TABLE` indexes the
/// protocol currently spoken (see [`set_active_protocol`]).
static BLOCK_TABLES: [OnceLock<Vec<BlockData>>; BLOCK_DATA.len()] =
    [const { OnceLock::new() }; BLOCK_DATA.len()];
/// The [`BLOCK_DATA`] slot holding the native version's tables: the initial
/// active table and the fallback for protocols without their own data.
const NATIVE_SLOT: usize = 0;
static ACTIVE_TABLE: std::sync::atomic::AtomicUsize =
    std::sync::atomic::AtomicUsize::new(NATIVE_SLOT);

/// Vanilla getFluidState overrides on blocks without a `waterlogged` property.
const IMPLICIT_WATER: [&str; 4] = ["seagrass", "tall_seagrass", "kelp", "kelp_plant"];

/// Loads the block-state table for the launched game version. Must be called
/// once at startup before any world/render code runs.
pub fn init(version: &str) {
    let protocol = pomme_protocol::ProtocolVersion::from_name(version)
        .map(|v| v.protocol)
        .unwrap_or_else(|| {
            tracing::warn!(
                "no block-state data for version {version}, using {} — expect state drift",
                pomme_protocol::version::NATIVE.name
            );
            pomme_protocol::version::NATIVE.protocol
        });
    set_active_protocol(protocol);
}

/// Switches the active table to the given protocol's, building it on first
/// use, so state ids from the wire are interpreted natively in that
/// version's id space (no chunk remapping). Patch releases sharing a
/// protocol number (26.1 through 26.1.2 are all 775) get the same table.
/// Only safe between worlds — meshes built against the previous table
/// interpret ids in the old id space.
pub fn set_active_protocol(protocol: i32) {
    let slot = prewarm_protocol(protocol);
    ACTIVE_TABLE.store(slot, std::sync::atomic::Ordering::Release);
}

/// Builds the given protocol's table if it isn't already, without switching
/// to it; safe at any time (e.g. from a server-list ping, ahead of the join).
pub fn prewarm_protocol(protocol: i32) -> usize {
    let slot = block_data_slot(protocol).unwrap_or(NATIVE_SLOT);
    BLOCK_TABLES[slot].get_or_init(|| build_table(&BLOCK_DATA[slot]));
    slot
}

/// The `BLOCK_DATA` slot serving a protocol, through `SHARED_BLOCK_DATA`.
fn block_data_slot(protocol: i32) -> Option<usize> {
    let protocol = SHARED_BLOCK_DATA
        .iter()
        .find(|&&(p, _)| p == protocol)
        .map_or(protocol, |&(_, shared)| shared);
    BLOCK_DATA.iter().position(|d| d.protocol == protocol)
}

fn load_behaviors() -> HashMap<String, BehaviorEntry> {
    serde_json::from_str(include_str!("data/block_behavior.json"))
        .expect("invalid block-behavior data")
}

fn build_table(data: &EmbeddedBlocks) -> Vec<BlockData> {
    let file: BlockFile = serde_json::from_str(data.blocks).expect("invalid block-state data");
    assert_eq!(
        pomme_protocol::ProtocolVersion::from_name(&file.version).map(|v| v.protocol),
        Some(data.protocol),
        "block data for {} is keyed to protocol {}",
        file.version,
        data.protocol
    );
    let behaviors = load_behaviors();
    let state_file: StateFile = serde_json::from_str(data.state).expect("invalid state data");
    assert_eq!(
        state_file.version, file.version,
        "state data is for a different version"
    );
    assert_eq!(
        state_file.state_count, file.state_count,
        "state data state count mismatch"
    );
    assert_eq!(
        state_file.blocks.len(),
        file.blocks.len(),
        "state data block count mismatch"
    );
    let masks: &'static [FaceMask] = Vec::leak(
        state_file
            .masks
            .iter()
            .map(|hex| decode_face_mask(hex))
            .collect(),
    );
    // The same handful of 6-mask tuples repeats across thousands of states;
    // dedupe them into leaked statics so each state stores one pointer.
    let mut tuples: HashMap<[u32; 6], &'static [FaceMask; 6]> = HashMap::new();
    let mut tuple = |indices: [u32; 6]| -> &'static [FaceMask; 6] {
        tuples
            .entry(indices)
            .or_insert_with(|| Box::leak(Box::new(indices.map(|i| masks[i as usize]))))
    };

    let mut interner: HashSet<&'static str> = HashSet::new();
    let mut intern = |s: &str| -> &'static str {
        match interner.get(s) {
            Some(&e) => e,
            None => {
                let leaked: &'static str = Box::leak(s.to_string().into_boxed_str());
                interner.insert(leaked);
                leaked
            }
        }
    };

    let mut table: Vec<BlockData> = Vec::with_capacity(file.state_count as usize);
    for (block, state_entry) in file.blocks.iter().zip(&state_file.blocks) {
        assert_eq!(
            block.first_id,
            table.len() as u32,
            "block-state data not dense at '{}'",
            block.name
        );
        assert_eq!(
            state_entry.name, block.name,
            "state data out of order at '{}'",
            block.name
        );
        let name = intern(&block.name);
        let behavior = match behaviors.get(&block.name) {
            Some(b) => BlockBehavior {
                destroy_time: b.destroy_time,
                requires_correct_tool_for_drops: b.requires_correct_tool,
            },
            None => {
                tracing::warn!("no behavior entry for block '{}', using defaults", name);
                DEFAULT_BEHAVIOR
            }
        };
        let props: Vec<(&'static str, Vec<&'static str>)> = block
            .props
            .iter()
            .map(|(k, vs)| (intern(k), vs.iter().map(|v| intern(v)).collect()))
            .collect();
        let is_air = matches!(block.name.as_str(), "air" | "cave_air" | "void_air");
        let collides = state_entry.c != 0;

        let count: u32 = props.iter().map(|(_, vs)| vs.len() as u32).product();
        let face_indices = light_face_indices(state_entry, count as usize);
        for offset in 0..count {
            let mut pairs = Vec::with_capacity(props.len());
            let mut stride = count;
            for (key, values) in &props {
                stride /= values.len() as u32;
                pairs.push((*key, values[(offset / stride) as usize % values.len()]));
            }
            let properties = PropMap::from_pairs(pairs);
            let fluid = state_fluid(name, &properties);
            let shape = compute_shape(name, &properties).map(Vec::into_boxed_slice);
            let outline = compute_outline(name, &properties).map(Vec::into_boxed_slice);
            let light = LightProps {
                emission: state_entry.e.get(offset as usize),
                dampening: state_entry.d.get(offset as usize),
                propagates_skylight_down: state_entry.p.get(offset as usize) != 0,
                can_occlude: state_entry.o.get(offset as usize) != 0,
                use_shape_for_light_occlusion: state_entry.u.get(offset as usize) != 0,
                face_occlusion: face_indices[offset as usize].map(&mut tuple),
            };
            table.push(BlockData {
                id: name,
                properties,
                behavior,
                shape,
                outline,
                is_air,
                collides,
                fluid,
                light,
            });
        }
    }

    assert_eq!(
        table.len() as u32,
        file.state_count,
        "block-state data table size mismatch for {}",
        file.version
    );
    table
}

fn decode_face_mask(hex: &str) -> FaceMask {
    assert_eq!(hex.len(), 64, "face mask must be 64 hex chars");
    std::array::from_fn(|v| {
        u16::from_str_radix(&hex[v * 4..v * 4 + 4], 16).expect("invalid face-mask hex")
    })
}

/// Expands a light entry's `f` field into per-state mask-dictionary tuples.
fn light_face_indices(entry: &StateEntry, count: usize) -> Vec<Option<[u32; 6]>> {
    let Some(f) = &entry.f else {
        return vec![None; count];
    };
    let arr = f
        .as_array()
        .unwrap_or_else(|| panic!("{}: face-mask field is not an array", entry.name));
    let parse_tuple = |values: &[serde_json::Value]| -> [u32; 6] {
        assert_eq!(values.len(), 6, "{}: face-mask tuple length", entry.name);
        std::array::from_fn(|i| {
            values[i]
                .as_u64()
                .unwrap_or_else(|| panic!("{}: non-numeric face-mask index", entry.name))
                as u32
        })
    };
    if arr.first().is_some_and(serde_json::Value::is_number) {
        // Uniform across the block: a single 6-index tuple.
        return vec![Some(parse_tuple(arr)); count];
    }
    assert_eq!(arr.len(), count, "{}: face-mask entry count", entry.name);
    arr.iter()
        .map(|v| {
            if v.is_null() {
                None
            } else {
                Some(parse_tuple(v.as_array().unwrap_or_else(|| {
                    panic!("{}: face-mask entry is not a tuple", entry.name)
                })))
            }
        })
        .collect()
}

fn state_fluid(name: &'static str, props: &PropMap) -> Fluid {
    match name {
        "water" | "lava" => {
            let level: u8 = props.get("level").and_then(|l| l.parse().ok()).unwrap_or(0);
            let kind = if name == "water" {
                FluidKind::Water
            } else {
                FluidKind::Lava
            };
            if level >= 8 {
                Fluid {
                    kind,
                    amount: 8,
                    falling: true,
                }
            } else {
                Fluid {
                    kind,
                    amount: 8 - level,
                    falling: false,
                }
            }
        }
        "bubble_column" => FULL_WATER,
        _ if IMPLICIT_WATER.contains(&name) => FULL_WATER,
        _ if props.get("waterlogged") == Some("true") => FULL_WATER,
        _ => NO_FLUID,
    }
}

fn table() -> &'static Vec<BlockData> {
    BLOCK_TABLES[ACTIVE_TABLE.load(std::sync::atomic::Ordering::Acquire)]
        .get()
        .expect("world::block::init must be called before use")
}

fn block_data(state: BlockState) -> &'static BlockData {
    static UNKNOWN: std::sync::LazyLock<BlockData> = std::sync::LazyLock::new(|| BlockData {
        id: "unknown",
        properties: PropMap::from_pairs(Vec::new()),
        behavior: DEFAULT_BEHAVIOR,
        shape: None,
        outline: None,
        is_air: false,
        collides: true,
        fluid: NO_FLUID,
        light: BEDROCK_LIGHT,
    });
    table().get(u32::from(state) as usize).unwrap_or(&UNKNOWN)
}

/// Every valid block state paired with its cached data, in id order.
fn all_states() -> impl Iterator<Item = (BlockState, &'static BlockData)> {
    table().iter().enumerate().map(|(id, data)| {
        let state = BlockState::try_from(id as u32).expect("table indices fit the id repr");
        (state, data)
    })
}

/// First declared state of the named block, e.g. the light engine's bedrock
/// fallback for unloaded-chunk reads.
pub(crate) fn first_state_of(name: &str) -> Option<BlockState> {
    all_states().find(|(_, d)| d.id == name).map(|(s, _)| s)
}

pub(crate) fn water_source_state() -> BlockState {
    all_states()
        .find(|(_, d)| d.id == "water" && d.properties.get("level") == Some("0"))
        .map(|(state, _)| state)
        .expect("vanilla water source state must exist")
}

/// Converts a wire-side numeric state id, validated against the loaded table.
pub fn try_state(id: u32) -> Option<BlockState> {
    if (id as usize) < table().len() {
        BlockState::try_from(id).ok()
    } else {
        None
    }
}

/// Vanilla LevelChunk's debug-world read override, including in Nether/End.
/// Built once per level from the active protocol table (the vanilla registry
/// order).
#[derive(Clone, Copy)]
pub(crate) struct DebugWorld {
    width: i32,
    height: i32,
    barrier: BlockState,
}

impl DebugWorld {
    pub fn new() -> Self {
        let count = table().len();
        let width = (count as f32).sqrt().ceil() as i32;
        Self {
            width,
            height: count.div_ceil(width as usize) as i32,
            // Barrier's first enumerated state is waterlogged; vanilla uses its dry default.
            barrier: all_states()
                .find(|(_, d)| d.id == "barrier" && d.properties.get("waterlogged") != Some("true"))
                .expect("vanilla debug world requires barrier")
                .0,
        }
    }

    pub fn state(self, x: i32, y: i32, z: i32) -> BlockState {
        if y == 60 {
            return self.barrier;
        }
        if y == 70 && x > 0 && z > 0 && x % 2 != 0 && z % 2 != 0 {
            let (x, z) = (x / 2, z / 2);
            // DebugLevelSource.getBlockStateFor uses inclusive grid bounds.
            if x <= self.width && z <= self.height {
                return try_state((x * self.width + z) as u32).unwrap_or(BlockState::AIR);
            }
        }
        BlockState::AIR
    }
}

pub fn block_id(state: BlockState) -> &'static str {
    block_data(state).id
}

pub fn block_properties(state: BlockState) -> &'static PropMap {
    &block_data(state).properties
}

pub fn block_behavior(state: BlockState) -> &'static BlockBehavior {
    &block_data(state).behavior
}

/// Vanilla `RedStoneWireBlock.getColorForPower`: dust tint for the state's
/// `power` value.
pub fn redstone_wire_rgb(state: BlockState) -> [f32; 3] {
    static COLORS: std::sync::LazyLock<[[f32; 3]; 16]> = std::sync::LazyLock::new(|| {
        std::array::from_fn(|power| {
            let f = power as f32 / 15.0;
            let red = f * 0.6 + if power > 0 { 0.4 } else { 0.3 };
            let green = (f * f * 0.7 - 0.5).clamp(0.0, 1.0);
            let blue = (f * f * 0.6 - 0.7).clamp(0.0, 1.0);
            [red, green, blue]
        })
    });
    let power: usize = block_properties(state)
        .get("power")
        .and_then(|p| p.parse().ok())
        .unwrap_or(0);
    COLORS[power.min(15)]
}

/// Vanilla `BlockTintSources.stem`: ARGB.color(age * 32, 255 - age * 8, age * 4).
/// The state table carries the canonical `age` property as a decimal string.
pub fn stem_rgb(state: BlockState) -> [f32; 3] {
    let age = block_properties(state)
        .get("age")
        .and_then(|value| value.parse::<u8>().ok())
        .unwrap_or(0)
        .min(7);
    [
        age as f32 * 32.0 / 255.0,
        (255.0 - age as f32 * 8.0) / 255.0,
        age as f32 * 4.0 / 255.0,
    ]
}

/// Vanilla `isAir`: includes cave and void air.
pub fn is_air(state: BlockState) -> bool {
    block_data(state).is_air
}

/// Whether the state's block collides with entities (vanilla `hasCollision`).
pub fn has_collision(state: BlockState) -> bool {
    block_data(state).collides
}

pub fn fluid(state: BlockState) -> Fluid {
    block_data(state).fluid
}

/// Whether two states carry the same renderable fluid type. Vanilla's
/// FluidRenderer culls by fluid type; amount/source remain available for the
/// separate height/flow calculation. This is independent of block-shape
/// occlusion so waterlogged solids participate too.
pub fn same_fluid(a: Fluid, b: Fluid) -> bool {
    a.kind != FluidKind::Empty && a.kind == b.kind
}

pub(crate) fn block_shape(state: BlockState) -> Option<&'static [LocalBox]> {
    block_data(state).shape.as_deref()
}

/// Outline shape for interaction raycasts (vanilla `getShape`), falling back to
/// the collision shape where the two agree. `None` is a full cube; an empty
/// slice is a block the pick ray passes through.
pub(crate) fn block_outline(state: BlockState) -> Option<&'static [LocalBox]> {
    let data = block_data(state);
    data.outline.as_deref().or(data.shape.as_deref())
}

/// Baked light properties for a state (vanilla `BlockStateBase` light cache).
pub fn light_props(state: BlockState) -> LightProps {
    block_data(state).light
}

/// Vanilla `LightEngine.isEmptyShape`: the state needs no voxel-shape
/// occlusion tests (full opaque cubes qualify — their opacity handles them).
pub fn is_empty_shape(state: BlockState) -> bool {
    let light = block_data(state).light;
    !light.can_occlude || !light.use_shape_for_light_occlusion
}

/// Vanilla `LightEngine.shapeOccludes(from, to, dir)` reduced to face masks:
/// whether `from`'s face and `to`'s opposite face together cover the full
/// face. `face` is the vanilla `Direction` ordinal (DOWN, UP, NORTH, SOUTH,
/// WEST, EAST); opposites pair as `face ^ 1`. Empty-shape states contribute
/// an empty mask, so two shapeless neighbors never occlude.
pub fn shape_occludes(from: BlockState, to: BlockState, face: usize) -> bool {
    let mask = |state: BlockState, face: usize| {
        block_data(state)
            .light
            .face_occlusion
            .map(|masks| &masks[face])
    };
    let a = mask(from, face);
    let b = mask(to, face ^ 1);
    if a.is_none() && b.is_none() {
        return false;
    }
    (0..16).all(|v| (a.map_or(0, |m| m[v]) | b.map_or(0, |m| m[v])) == 0xFFFF)
}

/// The block's state matching the given property values (unlisted properties
/// take whatever the first match has); shared with the light-engine tests.
#[cfg(test)]
pub(crate) fn find_state(name: &str, props: &[(&str, &str)]) -> BlockState {
    all_states()
        .find(|(s, d)| {
            d.id == name
                && props
                    .iter()
                    .all(|&(k, v)| block_properties(*s).get(k) == Some(v))
        })
        .unwrap_or_else(|| panic!("no state {name} {props:?}"))
        .0
}

#[cfg(test)]
mod tests {
    use super::*;

    fn setup() {
        init("26.2");
    }

    #[test]
    fn chest_states_decode() {
        setup();
        // Oracle from reference/26.2/generated/reports/blocks.json:
        // chest[type=single,facing=south,waterlogged=false] is id 3994 — the
        // state that previously decoded as facing=east under azalea's stale
        // 26.1 tables.
        let state = try_state(3994).unwrap();
        assert_eq!(block_id(state), "chest");
        let props = block_properties(state);
        assert_eq!(props.get("facing"), Some("south"));
        assert_eq!(props.get("type"), Some("single"));
        assert_eq!(props.get("waterlogged"), Some("false"));
    }

    #[test]
    fn new_26_2_blocks_resolve() {
        setup();
        assert!(all_states().any(|(_, d)| d.id == "copper_chest"));
        assert!(try_state(u32::MAX).is_none());
        let count = table().len() as u32;
        assert!(try_state(count).is_none());
        assert!(try_state(count - 1).is_some());
    }

    #[test]
    fn redstone_wire_colors() {
        setup();
        let unpowered = find_state("redstone_wire", &[("power", "0")]);
        assert_eq!(redstone_wire_rgb(unpowered), [0.3, 0.0, 0.0]);
        let full = redstone_wire_rgb(find_state("redstone_wire", &[("power", "15")]));
        for (got, want) in full.iter().zip([1.0, 0.2, 0.0]) {
            assert!((got - want).abs() < 1e-6, "{full:?}");
        }
    }

    #[test]
    fn stem_colors_follow_vanilla_age_formula() {
        setup();
        for age in 0..=7 {
            let state = find_state("pumpkin_stem", &[("age", &age.to_string())]);
            let expected = [
                age as f32 * 32.0 / 255.0,
                (255.0 - age as f32 * 8.0) / 255.0,
                age as f32 * 4.0 / 255.0,
            ];
            for (got, want) in stem_rgb(state).into_iter().zip(expected) {
                assert!((got - want).abs() < 1e-6, "age={age}: {got} != {want}");
            }
        }
    }

    #[test]
    fn fluid_states() {
        setup();
        let (still, _) = all_states()
            .find(|(s, d)| d.id == "water" && block_properties(*s).get("level") == Some("0"))
            .unwrap();
        let f = fluid(still);
        assert_eq!(f.kind, FluidKind::Water);
        assert_eq!(f.amount, 8);
        assert!(!f.falling);

        let (falling, _) = all_states()
            .find(|(s, d)| d.id == "water" && block_properties(*s).get("level") == Some("9"))
            .unwrap();
        assert!(fluid(falling).falling);

        let (logged, _) = all_states()
            .find(|(s, d)| {
                d.id == "oak_stairs" && block_properties(*s).get("waterlogged") == Some("true")
            })
            .unwrap();
        assert_eq!(fluid(logged).kind, FluidKind::Water);
        assert_eq!(fluid(logged).amount, 8);

        assert_eq!(fluid(BlockState::AIR).kind, FluidKind::Empty);
        assert!(same_fluid(f, fluid(logged)));
        assert!(same_fluid(f, fluid(falling)));
        assert!(!same_fluid(f, fluid(BlockState::AIR)));
    }

    #[test]
    fn collision_flags() {
        setup();
        // Oracles from reference/26.2/decompiled Blocks.java noCollision sites.
        assert!(!has_collision(BlockState::AIR));
        assert!(!has_collision(find_state("torch", &[])));
        assert!(!has_collision(find_state("water", &[("level", "0")])));
        assert!(!has_collision(find_state("oak_button", &[])));
        assert!(has_collision(find_state("stone", &[])));
        assert!(has_collision(find_state("oak_fence", &[])));
    }

    #[test]
    fn light_emission_values() {
        setup();
        // Oracles from reference/26.2/decompiled Blocks.java lightLevel sites.
        assert_eq!(light_props(find_state("torch", &[])).emission, 14);
        assert_eq!(light_props(find_state("glowstone", &[])).emission, 15);
        assert_eq!(
            light_props(find_state("redstone_lamp", &[("lit", "true")])).emission,
            15
        );
        assert_eq!(
            light_props(find_state("redstone_lamp", &[("lit", "false")])).emission,
            0
        );
        assert_eq!(
            light_props(find_state(
                "sea_pickle",
                &[("pickles", "3"), ("waterlogged", "true")]
            ))
            .emission,
            12
        );
        assert_eq!(
            light_props(find_state(
                "sea_pickle",
                &[("pickles", "3"), ("waterlogged", "false")]
            ))
            .emission,
            0
        );
        assert_eq!(
            light_props(find_state("cave_vines", &[("berries", "true")])).emission,
            14
        );
        assert_eq!(
            light_props(find_state("cave_vines", &[("berries", "false")])).emission,
            0
        );
        assert_eq!(
            light_props(find_state("light", &[("level", "7")])).emission,
            7
        );
    }

    #[test]
    fn light_dampening_values() {
        setup();
        let stone = light_props(find_state("stone", &[]));
        assert_eq!(stone.dampening, 15);
        assert!(stone.can_occlude);
        assert!(!stone.use_shape_for_light_occlusion);
        assert!(is_empty_shape(find_state("stone", &[])));

        assert_eq!(
            light_props(find_state("water", &[("level", "0")])).dampening,
            1
        );
        assert_eq!(light_props(find_state("oak_leaves", &[])).dampening, 1);
        let glass = light_props(find_state("glass", &[]));
        assert_eq!(glass.dampening, 0);
        assert!(glass.propagates_skylight_down);
        assert_eq!(light_props(BlockState::AIR).dampening, 0);
    }

    #[test]
    fn slab_face_occlusion() {
        setup();
        let top = find_state("oak_slab", &[("type", "top"), ("waterlogged", "false")]);
        let bottom = find_state("oak_slab", &[("type", "bottom"), ("waterlogged", "false")]);
        let double = find_state("oak_slab", &[("type", "double")]);
        let stone = find_state("stone", &[]);

        assert!(!is_empty_shape(top));
        assert!(!is_empty_shape(bottom));
        // Double slabs are solid-render full cubes: no shape tests needed.
        assert!(is_empty_shape(double));

        // Vanilla Direction ordinals: DOWN=0, UP=1.
        const DOWN: usize = 0;
        const UP: usize = 1;
        // A top slab's UP face is full; a bottom slab's DOWN face is full.
        assert!(shape_occludes(top, stone, UP));
        assert!(shape_occludes(bottom, stone, DOWN));
        // The open halves don't occlude.
        assert!(!shape_occludes(top, stone, DOWN));
        assert!(!shape_occludes(bottom, stone, UP));
        // Top slab above a bottom slab: neither shape touches the seam plane,
        // so both face slices are empty and the seam stays open.
        assert!(!shape_occludes(top, bottom, DOWN));
        const NORTH: usize = 2;
        // Side faces of two aligned bottom slabs cover only the lower half.
        assert!(!shape_occludes(bottom, bottom, NORTH));
    }

    /// Oracles from reference/26.2/decompiled: `SnowLayerBlock` is the only
    /// shape here whose `getShape` and `getCollisionShape` disagree, and
    /// `LiquidBlock`/`BubbleColumnBlock` return `Shapes.empty()`.
    #[test]
    fn outline_shapes() {
        setup();

        // One snow layer is 2/16 tall to look at but has no collision at all.
        let thin = find_state("snow", &[("layers", "1")]);
        assert_eq!(block_shape(thin), Some(&[][..]));
        assert_eq!(
            block_outline(thin),
            Some(&[[0.0, 0.0, 0.0, 1.0, 2.0 / 16.0, 1.0]][..])
        );
        // Eight layers fill the cell visually but collide one layer short.
        let full = find_state("snow", &[("layers", "8")]);
        assert_eq!(
            block_shape(full),
            Some(&[[0.0, 0.0, 0.0, 1.0, 14.0 / 16.0, 1.0]][..])
        );
        assert_eq!(
            block_outline(full),
            Some(&[[0.0, 0.0, 0.0, 1.0, 1.0, 1.0]][..])
        );

        // Fluids are clipped through, not targeted.
        for id in ["water", "lava"] {
            assert_eq!(
                block_outline(find_state(id, &[("level", "0")])),
                Some(&[][..])
            );
        }
        assert_eq!(
            block_outline(find_state("bubble_column", &[])),
            Some(&[][..])
        );

        // Everywhere else the collision shape doubles as the outline.
        let slab = find_state("oak_slab", &[("type", "bottom"), ("waterlogged", "false")]);
        assert_eq!(block_outline(slab), block_shape(slab));
        assert_eq!(block_outline(find_state("stone", &[])), None);
    }

    /// Builds every embedded table so the block/light cross-checks fire for
    /// all versions, not just the one `setup` activates.
    #[test]
    fn all_tables_build() {
        for data in BLOCK_DATA {
            build_table(data);
        }
    }

    /// Every block name in every embedded version table has an entry in the
    /// shared behavior and sound tables (a missing one would silently fall
    /// back to instant-break defaults and stone sounds), and every table key
    /// names a block in some embedded version (an orphan is a typo'd or
    /// stale entry — the defect class the legacy crop sound keys were).
    #[test]
    fn shared_tables_cover_all_versions() {
        let behaviors = load_behaviors();
        let mut known = HashSet::new();
        for data in BLOCK_DATA {
            let file: BlockFile = serde_json::from_str(data.blocks).unwrap();
            for block in &file.blocks {
                assert!(
                    behaviors.contains_key(&block.name),
                    "no behavior entry for '{}' ({})",
                    block.name,
                    file.version
                );
                assert!(
                    sound::BLOCK_SOUNDS.contains_key(&block.name),
                    "no sound entry for '{}' ({})",
                    block.name,
                    file.version
                );
                known.insert(block.name.clone());
            }
        }
        for key in behaviors.keys() {
            assert!(known.contains(key), "orphaned behavior entry '{key}'");
        }
        for key in sound::BLOCK_SOUNDS.keys() {
            assert!(known.contains(key), "orphaned sound entry '{key}'");
        }
    }

    /// Every launchable version has a block table (its own or a shared one);
    /// `prewarm_protocol` would otherwise fall back to 26.2's silently.
    #[test]
    fn block_data_covers_versions() {
        for v in pomme_protocol::version::VERSIONS {
            assert!(block_data_slot(v.protocol).is_some(), "{}", v.name);
        }
    }

    #[test]
    fn native_slot() {
        let native = pomme_protocol::version::NATIVE.protocol;
        assert_eq!(block_data_slot(native), Some(NATIVE_SLOT));
    }
}
