//! Per-version tables of the client-facing static registries and the
//! cross-version id remaps built from them.
//!
//! Static-registry ids (entities, sounds, items, ...) are implicit from
//! registration order and shift between game versions. The tables are the
//! ordered entry names (wire id == index) generated by
//! `tools/protogen registries` from the data-generator reports; a remap
//! translates another version's ids into the native version's id space so
//! the rest of the client stays single-version.

use std::collections::HashMap;
use std::sync::OnceLock;

use crate::version::{EMBEDDED, NATIVE, ProtocolVersion};

/// Declares `ClientRegistry` with its `ALL` list and report keys from one
/// table, so the variants, their order and their keys can't drift apart.
macro_rules! client_registries {
    ($(#[$meta:meta])* $($variant:ident => $key:literal,)*) => {
        $(#[$meta])*
        #[derive(Clone, Copy, PartialEq, Eq, Debug)]
        pub enum ClientRegistry {
            $($variant,)*
        }

        impl ClientRegistry {
            pub const ALL: [ClientRegistry; [$($key),*].len()] =
                [$(ClientRegistry::$variant),*];

            fn key(self) -> &'static str {
                match self {
                    $(ClientRegistry::$variant => $key,)*
                }
            }
        }
    };
}

client_registries! {
    /// The registries carried in `registries-<version>.json` (matching
    /// protogen's `CLIENT_REGISTRIES`): the ones whose numeric ids reach the
    /// client inside game packets.
    Attribute => "attribute",
    BlockEntityType => "block_entity_type",
    CommandArgumentType => "command_argument_type",
    ConsumeEffectType => "consume_effect_type",
    DataComponentType => "data_component_type",
    DebugSubscription => "debug_subscription",
    EntityType => "entity_type",
    GameEvent => "game_event",
    Item => "item",
    Menu => "menu",
    NumberFormatType => "number_format_type",
    ParticleType => "particle_type",
    PositionSourceType => "position_source_type",
    RecipeDisplay => "recipe_display",
    RecipeSerializer => "recipe_serializer",
    SlotDisplay => "slot_display",
    SoundEvent => "sound_event",
}

impl ClientRegistry {
    /// First protocol carrying this registry; older tables omit it.
    fn since(self) -> i32 {
        match self {
            // Scoreboard number formats arrived in 1.20.3.
            ClientRegistry::NumberFormatType => 765,
            // Item components arrived in 1.20.5.
            ClientRegistry::DataComponentType => 766,
            // Recipe displays and consume effects arrived in 1.21.2.
            ClientRegistry::RecipeDisplay
            | ClientRegistry::SlotDisplay
            | ClientRegistry::ConsumeEffectType => 768,
            // Debug subscriptions arrived in 1.21.9.
            ClientRegistry::DebugSubscription => 773,
            _ => 0,
        }
    }
}

/// One version's ordered registry entry names (wire id == index).
pub struct RegistryTable {
    version: ProtocolVersion,
    registries: [Vec<String>; ClientRegistry::ALL.len()],
}

#[derive(serde::Deserialize)]
struct TableFile {
    version: String,
    protocol: i32,
    registries: HashMap<String, Vec<String>>,
}

impl RegistryTable {
    /// The table for the version the client speaks natively.
    pub fn native() -> &'static RegistryTable {
        Self::for_protocol(NATIVE.protocol).expect("native registry table is embedded")
    }

    /// The table for a launchable protocol number, or `None` for versions
    /// without an embedded table.
    pub fn for_protocol(protocol: i32) -> Option<&'static RegistryTable> {
        static TABLES: [OnceLock<RegistryTable>; EMBEDDED.len()] =
            [const { OnceLock::new() }; EMBEDDED.len()];
        crate::version::embedded_get(protocol, &TABLES, |e| {
            Self::parse(e.registries, e.version)
                .unwrap_or_else(|err| panic!("embedded {} registry table: {err}", e.version.name))
        })
    }

    fn parse(json: &str, expected: ProtocolVersion) -> Result<Self, String> {
        let mut file: TableFile = serde_json::from_str(json).map_err(|e| e.to_string())?;
        if file.version != expected.name || file.protocol != expected.protocol {
            return Err(format!(
                "table is {}/{}, expected {}/{}",
                file.version, file.protocol, expected.name, expected.protocol
            ));
        }
        let mut registries: [Vec<String>; ClientRegistry::ALL.len()] = Default::default();
        for reg in ClientRegistry::ALL {
            // Absent below the registry's `since` is legitimate; anywhere else
            // accepting it would silently remap every id in it to None.
            let Some(names) = file.registries.remove(reg.key()) else {
                if expected.protocol >= reg.since() {
                    return Err(format!("missing registry {}", reg.key()));
                }
                continue;
            };
            if names.is_empty() {
                return Err(format!("empty registry {}", reg.key()));
            }
            registries[reg as usize] = names;
        }
        Ok(Self {
            version: expected,
            registries,
        })
    }

    pub fn version(&self) -> ProtocolVersion {
        self.version
    }

    pub fn names(&self, reg: ClientRegistry) -> &[String] {
        &self.registries[reg as usize]
    }

    pub fn name_of(&self, reg: ClientRegistry, id: u32) -> Option<&str> {
        self.names(reg).get(id as usize).map(String::as_str)
    }

    pub fn id_of(&self, reg: ClientRegistry, name: &str) -> Option<u32> {
        let id = self.names(reg).iter().position(|n| n == name)?;
        Some(id as u32)
    }
}

/// Configuration-phase dynamic registries. Unlike `RegistryTable`, these ids
/// belong to the server's ordered registry-data entries, not a game version.
/// A duplicate name is deliberately unresolvable (never guess an id).
#[derive(Default, Clone, Debug)]
pub struct DynamicRegistries {
    entries: HashMap<String, Vec<String>>,
}

impl DynamicRegistries {
    pub fn clear(&mut self) {
        self.entries.clear();
    }

    pub fn replace(&mut self, registry: &str, names: Vec<String>) {
        self.entries.insert(registry.to_owned(), names);
    }

    pub fn id_of(&self, registry: &str, name: &str) -> Option<u32> {
        let names = self.entries.get(registry)?;
        let name = if name.contains(':') {
            name.to_owned()
        } else {
            format!("minecraft:{name}")
        };
        let mut ids = names.iter().enumerate().filter(|(_, n)| *n == &name);
        let (id, _) = ids.next()?;
        ids.next().is_none().then_some(id as u32)
    }
}

/// Directed id remaps between two versions' registries, matched by entry
/// name. `None` marks ids without an equivalent in the target version
/// (entries added/removed since, or out of range).
pub struct RegistryRemaps {
    maps: [Vec<Option<u32>>; ClientRegistry::ALL.len()],
}

/// Entry renames name-matching can't bridge, applied both directions
/// (26.x renamed the chain item to iron_chain, 1.20.3 renamed the grass
/// block/item to short_grass).
const RENAMED: &[(ClientRegistry, &str, &str)] = &[
    (ClientRegistry::Item, "chain", "iron_chain"),
    (ClientRegistry::Item, "grass", "short_grass"),
];

impl RegistryRemaps {
    /// Remaps from `protocol`'s id space to the native version's (for
    /// inbound packets), or `None` for versions without an embedded registry
    /// table. For the native version itself this is an identity map.
    pub fn to_native(protocol: i32) -> Option<&'static RegistryRemaps> {
        static REMAPS: [OnceLock<RegistryRemaps>; EMBEDDED.len()] =
            [const { OnceLock::new() }; EMBEDDED.len()];
        crate::version::embedded_get(protocol, &REMAPS, |_| {
            Self::build(Self::embedded_table(protocol), RegistryTable::native())
        })
    }

    /// Remaps from the native version's id space to `protocol`'s (for
    /// outbound packets); the mirror of [`Self::to_native`].
    pub fn from_native(protocol: i32) -> Option<&'static RegistryRemaps> {
        static REMAPS: [OnceLock<RegistryRemaps>; EMBEDDED.len()] =
            [const { OnceLock::new() }; EMBEDDED.len()];
        crate::version::embedded_get(protocol, &REMAPS, |_| {
            Self::build(RegistryTable::native(), Self::embedded_table(protocol))
        })
    }

    fn embedded_table(protocol: i32) -> &'static RegistryTable {
        RegistryTable::for_protocol(protocol).expect("embedded registry table")
    }

    fn build(from: &RegistryTable, to: &RegistryTable) -> Self {
        let maps = ClientRegistry::ALL.map(|reg| {
            let to_ids: HashMap<&str, u32> = to
                .names(reg)
                .iter()
                .enumerate()
                .map(|(id, name)| (name.as_str(), id as u32))
                .collect();
            from.names(reg)
                .iter()
                .map(|name| {
                    to_ids.get(name.as_str()).copied().or_else(|| {
                        let alias = RENAMED.iter().find_map(|&(r, a, b)| {
                            if r != reg {
                                None
                            } else if name == a {
                                Some(b)
                            } else if name == b {
                                Some(a)
                            } else {
                                None
                            }
                        });
                        if let Some(alias) = alias {
                            return to_ids.get(alias).copied();
                        }
                        // 1.21.2 renamed every attribute by dropping its
                        // category prefix (generic.armor -> armor); match on
                        // the last dot segment for that registry only (sound
                        // names contain legitimate dots).
                        //
                        // TODO: stripping bridges one way only, so every
                        // attribute remap through `from_native` to a pre-1.21.2
                        // version is None (26.2 `max_health` misses 1.20.6's
                        // `generic.max_health`). Dormant while only Item and
                        // DataComponentType go outbound. Re-adding a prefix
                        // needs the target's own category, so the fix is a
                        // name-keyed lookup rather than a transform.
                        if reg != ClientRegistry::Attribute {
                            return None;
                        }
                        let stripped = name.rsplit('.').next()?;
                        (stripped != name).then(|| to_ids.get(stripped).copied())?
                    })
                })
                .collect()
        });
        Self { maps }
    }

    /// The target-version id for `id` in the source version's `reg`, or
    /// `None` if the entry has no equivalent (callers drop or ignore those).
    pub fn remap(&self, reg: ClientRegistry, id: u32) -> Option<u32> {
        self.maps[reg as usize].get(id as usize).copied().flatten()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn dynamic_registry_order_replace_and_ambiguity() {
        let mut registries = DynamicRegistries::default();
        registries.replace(
            "minecraft:enchantment",
            vec!["minecraft:sharpness".into(), "minecraft:efficiency".into()],
        );
        assert_eq!(
            registries.id_of("minecraft:enchantment", "efficiency"),
            Some(1)
        );
        assert_eq!(registries.id_of("minecraft:enchantment", "unknown"), None);
        registries.replace("minecraft:mob_effect", vec!["minecraft:speed".into()]);
        registries.replace(
            "minecraft:enchantment",
            vec!["minecraft:efficiency".into(), "minecraft:efficiency".into()],
        );
        assert_eq!(
            registries.id_of("minecraft:enchantment", "efficiency"),
            None
        );
        assert_eq!(registries.id_of("minecraft:mob_effect", "speed"), Some(0));
        registries.clear();
        assert_eq!(
            registries.id_of("minecraft:enchantment", "efficiency"),
            None
        );
        assert_eq!(registries.id_of("minecraft:mob_effect", "speed"), None);
    }

    /// The remap under test plus its endpoint tables.
    fn setup(
        protocol: i32,
    ) -> (
        &'static RegistryRemaps,
        &'static RegistryTable,
        &'static RegistryTable,
    ) {
        (
            RegistryRemaps::to_native(protocol).unwrap(),
            RegistryTable::for_protocol(protocol).unwrap(),
            RegistryTable::native(),
        )
    }

    /// An entry the native version removed or renamed has no remap.
    fn assert_unmapped(r: &RegistryRemaps, from: &RegistryTable, reg: ClientRegistry, name: &str) {
        let id = from.names(reg).iter().position(|n| n == name).unwrap() as u32;
        assert_eq!(r.remap(reg, id), None);
    }

    /// The bed block entity was removed in 26.2; its id has no remap.
    fn assert_bed_unmapped(r: &RegistryRemaps, from: &RegistryTable) {
        assert_unmapped(r, from, ClientRegistry::BlockEntityType, "bed");
    }

    /// The divergence anchors every version below 1.21.11 shares: 26.x
    /// inserted air_drag_modifier at attribute 0, 1.21.11 inserted
    /// camel_husk at entity 20 and use_effects at component 5 (far earlier
    /// than 1.21.11's own divergence at 41, so the raw item-stack
    /// limitation in translate.rs covers common components like custom_name
    /// on these versions), and particle ids diverge right after bubble (3).
    fn assert_pre_1_21_11_anchors(r: &RegistryRemaps, from: &RegistryTable) {
        assert_eq!(from.name_of(ClientRegistry::Attribute, 0), Some("armor"));
        assert_eq!(r.remap(ClientRegistry::Attribute, 0), Some(1));
        assert_eq!(from.name_of(ClientRegistry::EntityType, 20), Some("cat"));
        assert_eq!(r.remap(ClientRegistry::EntityType, 19), Some(19));
        assert_eq!(r.remap(ClientRegistry::EntityType, 20), Some(21));
        assert_eq!(r.remap(ClientRegistry::ParticleType, 3), Some(3));
        assert_ne!(r.remap(ClientRegistry::ParticleType, 4), Some(4));
        assert_eq!(
            from.name_of(ClientRegistry::DataComponentType, 5),
            Some("custom_name")
        );
        assert_eq!(r.remap(ClientRegistry::DataComponentType, 4), Some(4));
        assert_eq!(r.remap(ClientRegistry::DataComponentType, 5), Some(6));
    }

    /// 26.x renamed the chain item to iron_chain; `RENAMED` bridges it in
    /// both directions.
    fn assert_chain_remapped(r: &RegistryRemaps, from: &RegistryTable) {
        let items = |t: &RegistryTable, name| {
            t.names(ClientRegistry::Item)
                .iter()
                .position(|n| n == name)
                .unwrap() as u32
        };
        let (id, target) = (
            items(from, "chain"),
            items(RegistryTable::native(), "iron_chain"),
        );
        assert_eq!(r.remap(ClientRegistry::Item, id), Some(target));
        let rev = RegistryRemaps::from_native(from.version().protocol).unwrap();
        assert_eq!(rev.remap(ClientRegistry::Item, target), Some(id));
    }

    /// Every remapped id resolves to the same entry name in the target table
    /// (modulo the attribute prefix-strip alias).
    fn assert_round_trips(r: &RegistryRemaps, from: &RegistryTable, to: &RegistryTable) {
        for reg in ClientRegistry::ALL {
            for (id, name) in from.names(reg).iter().enumerate() {
                if let Some(new_id) = r.remap(reg, id as u32) {
                    let target = to.name_of(reg, new_id);
                    let renamed = RENAMED.iter().any(|&(rr, a, b)| {
                        rr == reg
                            && ((name == a && target == Some(b))
                                || (name == b && target == Some(a)))
                    });
                    assert!(
                        target == Some(name.as_str())
                            || renamed
                            || (reg == ClientRegistry::Attribute
                                && target == name.rsplit('.').next()),
                        "{reg:?} {id}"
                    );
                }
            }
        }
    }

    /// Anchor checks against the 26.3 -> 26.2 registry diff, the first remap
    /// from a version newer than native (spot-checked by hand against the two
    /// data-generator reports). Entries 26.3 added have no native id; ids
    /// below each insertion are stable.
    #[test]
    fn remap_26_3_anchors() {
        let (r, from, to) = setup(777);

        // cushion was inserted at entity id 33, the poplar boats at 106.
        assert_eq!(
            from.name_of(ClientRegistry::EntityType, 33),
            Some("cushion")
        );
        assert_eq!(r.remap(ClientRegistry::EntityType, 32), Some(32));
        assert_eq!(r.remap(ClientRegistry::EntityType, 34), Some(33));
        assert_eq!(r.remap(ClientRegistry::EntityType, 160), Some(157));
        assert_unmapped(r, from, ClientRegistry::EntityType, "cushion");

        // Items diverge at poplar_planks (72).
        assert_eq!(r.remap(ClientRegistry::Item, 71), Some(71));
        assert_unmapped(r, from, ClientRegistry::Item, "poplar_planks");
        assert_eq!(r.remap(ClientRegistry::Item, 73), Some(72));
        assert_eq!(r.remap(ClientRegistry::Item, 1657), Some(1536));

        // The three poplar leaf particles sit where tinted_leaves was (43).
        assert_eq!(r.remap(ClientRegistry::ParticleType, 42), Some(42));
        assert_unmapped(r, from, ClientRegistry::ParticleType, "red_poplar_leaves");
        assert_eq!(r.remap(ClientRegistry::ParticleType, 46), Some(43));

        // 26.3 replaced swing_animation (26.2's 40) with attack_animation and
        // interact_animation, inserted block_transformer and villager_food at
        // 43 and compostable, cooking_fuel, brewing_fuel and mob_visibility
        // after break_sound, dropped map_color (26.2's 45), and appended
        // provides_pottery_pattern through cushion/color, so component ids
        // diverge from 40.
        assert_eq!(
            to.name_of(ClientRegistry::DataComponentType, 40),
            Some("swing_animation")
        );
        assert_eq!(r.remap(ClientRegistry::DataComponentType, 39), Some(39));
        assert_unmapped(
            r,
            from,
            ClientRegistry::DataComponentType,
            "attack_animation",
        );
        for (wire, native, name) in [
            (42, 41, "additional_trade_cost"),
            (45, 42, "stored_enchantments"),
            (48, 46, "map_id"),
            (72, 70, "profile"),
            (116, 110, "shulker/color"),
        ] {
            assert_eq!(
                from.name_of(ClientRegistry::DataComponentType, wire),
                Some(name)
            );
            assert_eq!(
                r.remap(ClientRegistry::DataComponentType, wire),
                Some(native)
            );
        }
        assert_unmapped(
            RegistryRemaps::from_native(from.version().protocol).unwrap(),
            to,
            ClientRegistry::DataComponentType,
            "map_color",
        );

        // Four cushion sounds were inserted at 492; the other 19 are appended.
        assert_eq!(r.remap(ClientRegistry::SoundEvent, 491), Some(491));
        assert_unmapped(r, from, ClientRegistry::SoundEvent, "entity.cushion.break");
        assert_eq!(r.remap(ClientRegistry::SoundEvent, 496), Some(492));
        assert_eq!(r.remap(ClientRegistry::SoundEvent, 1990), None);

        for reg in [
            ClientRegistry::Attribute,
            ClientRegistry::BlockEntityType,
            ClientRegistry::GameEvent,
        ] {
            assert_eq!(from.names(reg), to.names(reg));
        }
        assert_round_trips(r, from, to);
    }

    /// Anchors hand-checked against the 26.1/26.2 `registries.json` report
    /// diff (insertion points and the one removed entry).
    #[test]
    fn remap_26_1_anchors() {
        let (r, from, to) = setup(775);

        // 26.2 inserted air_drag_modifier at attribute id 0.
        assert_eq!(from.name_of(ClientRegistry::Attribute, 0), Some("armor"));
        assert_eq!(to.name_of(ClientRegistry::Attribute, 1), Some("armor"));
        assert_eq!(r.remap(ClientRegistry::Attribute, 0), Some(1));

        // 26.2 inserted sulfur_cube at entity id 130; ids below are stable.
        assert_eq!(
            from.name_of(ClientRegistry::EntityType, 130),
            Some("tadpole")
        );
        assert_eq!(r.remap(ClientRegistry::EntityType, 129), Some(129));
        assert_eq!(r.remap(ClientRegistry::EntityType, 130), Some(131));

        assert_bed_unmapped(r, from);

        // Particle ids diverge right after bubble (id 3 in both).
        assert_eq!(r.remap(ClientRegistry::ParticleType, 3), Some(3));
        assert_eq!(from.name_of(ClientRegistry::ParticleType, 4), Some("cloud"));
        assert_eq!(
            to.name_of(ClientRegistry::ParticleType, 4),
            Some("sulfur_bubbles")
        );
        assert_ne!(r.remap(ClientRegistry::ParticleType, 4), Some(4));

        // Out-of-range source ids don't remap.
        assert_eq!(r.remap(ClientRegistry::SoundEvent, 100_000), None);

        assert_round_trips(r, from, to);
    }

    /// Anchor checks against the 1.21.11 -> 26.2 registry diff (spot-checked
    /// by hand against the two data-generator reports).
    #[test]
    fn remap_1_21_11_anchors() {
        let (r, from, to) = setup(774);

        // 26.x inserted air_drag_modifier at attribute id 0.
        assert_eq!(from.name_of(ClientRegistry::Attribute, 0), Some("armor"));
        assert_eq!(r.remap(ClientRegistry::Attribute, 0), Some(1));

        // sulfur_cube landed at entity id 130; ids below are stable.
        assert_eq!(
            from.name_of(ClientRegistry::EntityType, 130),
            Some("tadpole")
        );
        assert_eq!(r.remap(ClientRegistry::EntityType, 129), Some(129));
        assert_eq!(r.remap(ClientRegistry::EntityType, 130), Some(131));

        assert_bed_unmapped(r, from);

        // Particle ids diverge right after bubble (id 3 in both).
        assert_eq!(r.remap(ClientRegistry::ParticleType, 3), Some(3));
        assert_ne!(r.remap(ClientRegistry::ParticleType, 4), Some(4));

        // Component ids diverge at 41, where 26.x inserted
        // additional_trade_cost; this is where inbound item components start
        // decoding under the wrong codec (see translate.rs).
        assert_eq!(
            from.name_of(ClientRegistry::DataComponentType, 41),
            Some("stored_enchantments")
        );
        assert_eq!(r.remap(ClientRegistry::DataComponentType, 40), Some(40));
        assert_eq!(r.remap(ClientRegistry::DataComponentType, 41), Some(42));

        assert_round_trips(r, from, to);
    }

    /// Anchor checks against the 1.21.10 -> 26.2 registry diff (spot-checked
    /// by hand against the two data-generator reports). 1.21.11 added the
    /// nautilus/spear content drop, so 1.21.10 diverges earlier than 1.21.11
    /// in several registries.
    #[test]
    fn remap_1_21_10_anchors() {
        let (r, from, to) = setup(773);

        assert_pre_1_21_11_anchors(r, from);
        assert_eq!(r.remap(ClientRegistry::EntityType, 127), Some(131)); // tadpole
        assert_bed_unmapped(r, from);

        assert_round_trips(r, from, to);
    }

    /// Anchor checks against the 1.21.8 -> 26.2 registry diff (spot-checked
    /// by hand against the two data-generator reports). Divergence points
    /// match 1.21.10's (entity 20, component 5, particle 4); tadpole sits
    /// two lower than on 1.21.10 because 1.21.9 added copper_golem and
    /// mannequin, and the `chain` item was renamed by 26.x.
    #[test]
    fn remap_1_21_8_anchors() {
        let (r, from, to) = setup(772);

        assert_pre_1_21_11_anchors(r, from);
        assert_eq!(r.remap(ClientRegistry::EntityType, 125), Some(131)); // tadpole
        assert_bed_unmapped(r, from);

        assert_chain_remapped(r, from);

        assert_round_trips(r, from, to);
    }

    /// 1.21.6's registries match 1.21.8's (whose 26.2 anchors are pinned
    /// above) except the lava_chicken music disc and sound 1.21.7 inserted
    /// at item 1256 / sound 939, sitting the later ids one lower; asserted
    /// in full against the 1.21.8 table.
    #[test]
    fn remap_1_21_6_anchors() {
        let (r, from, to) = setup(771);
        let from_772 = RegistryTable::for_protocol(772).unwrap();

        for reg in ClientRegistry::ALL {
            let (a, b) = (from.names(reg), from_772.names(reg));
            let insert = match reg {
                ClientRegistry::Item => 1256,
                ClientRegistry::SoundEvent => 939,
                _ => {
                    assert_eq!(a, b, "{reg:?}");
                    continue;
                }
            };
            assert_eq!(a[..insert], b[..insert], "{reg:?}");
            assert_eq!(a[insert..], b[insert + 1..], "{reg:?}");
        }

        // The disc slot lava_chicken later takes.
        assert_eq!(
            from.name_of(ClientRegistry::Item, 1256),
            Some("music_disc_mall")
        );
        assert_eq!(r.remap(ClientRegistry::Item, 1256), Some(1348));

        assert_round_trips(r, from, to);
    }

    /// Anchor checks against the 1.21.5 -> 26.2 registry diff (spot-checked
    /// by hand against the two data-generator reports). 1.21.6 added the
    /// happy ghast (before tadpole), three waypoint/camera attributes, 19
    /// items and 29 sounds, and 26.2 dropped four 1.21.5 sounds along with
    /// the usual bed/chain renames.
    #[test]
    fn remap_1_21_5_anchors() {
        let (r, from, to) = setup(770);

        assert_pre_1_21_11_anchors(r, from);
        assert_eq!(r.remap(ClientRegistry::EntityType, 124), Some(131)); // tadpole
        assert_bed_unmapped(r, from);
        assert_chain_remapped(r, from);
        for sound in ["block.sand.wind", "entity.leash_knot.break"] {
            assert_unmapped(r, from, ClientRegistry::SoundEvent, sound);
        }

        assert_round_trips(r, from, to);
    }

    /// Anchor checks against the 1.21.4 -> 26.2 registry diff (spot-checked
    /// by hand against the two data-generator reports). 1.21.5 was a content
    /// release (31 data components, the spring-drop entities/items/sounds)
    /// that itself dropped the thrown `potion` entity for the splash and
    /// lingering split, both tooltip components and `entity.wolf.howl`;
    /// 26.2 dropped three further sounds, along with the usual bed/chain
    /// renames.
    #[test]
    fn remap_1_21_4_anchors() {
        let (r, from, to) = setup(769);

        assert_pre_1_21_11_anchors(r, from);
        assert_eq!(r.remap(ClientRegistry::EntityType, 123), Some(131)); // tadpole
        assert_bed_unmapped(r, from);
        assert_chain_remapped(r, from);
        assert_unmapped(r, from, ClientRegistry::EntityType, "potion");
        for component in ["hide_tooltip", "hide_additional_tooltip"] {
            assert_unmapped(r, from, ClientRegistry::DataComponentType, component);
        }
        assert_unmapped(r, from, ClientRegistry::SoundEvent, "entity.wolf.howl");

        assert_round_trips(r, from, to);
    }

    /// Anchor checks against the 1.21.3 -> 26.2 registry diff. Nearly
    /// 1.21.4's registries: 1.21.4 only removed `creaking_transient`
    /// (entity 30 here), shifting the later entity ids one higher than
    /// 1.21.4's.
    #[test]
    fn remap_1_21_3_anchors() {
        let (r, from, to) = setup(768);

        assert_pre_1_21_11_anchors(r, from);
        assert_eq!(r.remap(ClientRegistry::EntityType, 124), Some(131)); // tadpole
        assert_bed_unmapped(r, from);
        assert_chain_remapped(r, from);
        assert_unmapped(r, from, ClientRegistry::EntityType, "potion");
        assert_unmapped(r, from, ClientRegistry::EntityType, "creaking_transient");
        assert_unmapped(r, from, ClientRegistry::SoundEvent, "entity.wolf.howl");

        assert_round_trips(r, from, to);
    }

    /// The anchors 1.20.5 through 1.21.1 share: 1.21.2 renamed every
    /// attribute by dropping its category prefix (covered by the alias,
    /// pinned per version at its `generic.max_health` index), split
    /// `boat`/`chest_boat` per wood type (shifting entity ids from 0, where
    /// the boats sort alphabetically), and renamed
    /// `fire_resistant`/`item.goat_horn.play`; particle and component
    /// divergence points match the later 1.21.x versions.
    fn assert_pre_1_21_2_anchors(r: &RegistryRemaps, from: &RegistryTable, max_health: u32) {
        assert_eq!(
            from.name_of(ClientRegistry::Attribute, max_health),
            Some("generic.max_health")
        );
        assert_eq!(r.remap(ClientRegistry::Attribute, max_health), Some(23));

        assert_eq!(from.name_of(ClientRegistry::EntityType, 15), Some("cat"));
        assert_eq!(r.remap(ClientRegistry::EntityType, 15), Some(21));
        assert_eq!(r.remap(ClientRegistry::EntityType, 104), Some(131)); // tadpole

        assert_bed_unmapped(r, from);
        assert_chain_remapped(r, from);
        assert_unmapped(r, from, ClientRegistry::EntityType, "boat");
        assert_unmapped(r, from, ClientRegistry::EntityType, "chest_boat");
        assert_unmapped(r, from, ClientRegistry::EntityType, "potion");
        assert_unmapped(r, from, ClientRegistry::DataComponentType, "fire_resistant");
        assert_unmapped(r, from, ClientRegistry::SoundEvent, "item.goat_horn.play");

        assert_eq!(r.remap(ClientRegistry::ParticleType, 3), Some(3));
        assert_ne!(r.remap(ClientRegistry::ParticleType, 4), Some(4));
        assert_eq!(r.remap(ClientRegistry::DataComponentType, 4), Some(4));
        assert_eq!(r.remap(ClientRegistry::DataComponentType, 5), Some(6));
    }

    #[test]
    fn remap_1_21_1_anchors() {
        let (r, from, to) = setup(767);
        assert_pre_1_21_2_anchors(r, from, 18);
        assert_round_trips(r, from, to);
    }

    /// 1.20.6 shares 1.21.1's anchors; of the nine attributes 1.21 added,
    /// `generic.burning_time` and `generic.explosion_knockback_resistance`
    /// come ahead of `generic.max_health` and shift it 16 -> 18.
    #[test]
    fn remap_1_20_6_anchors() {
        let (r, from, to) = setup(766);
        assert_pre_1_21_2_anchors(r, from, 16);
        assert_round_trips(r, from, to);
    }

    /// The anchors 1.20.1 and 1.20.2 share: attributes are in pre-1.20.3
    /// registration order (max_health first), 1.20.3 renamed the grass item
    /// to short_grass (bridged by `RENAMED`), and no component registry
    /// exists yet. Their item, entity, particle and block-entity registries
    /// are byte-identical; 1.20.2 only adds an attribute after the pinned one
    /// and eleven sponge sounds, and reshuffles the game-event registry
    /// (entity_roar and entity_shake merged into entity_action, unequip
    /// added).
    fn assert_pre_1_20_3_anchors(r: &RegistryRemaps, from: &RegistryTable, to: &RegistryTable) {
        assert_eq!(
            from.name_of(ClientRegistry::Attribute, 0),
            Some("generic.max_health")
        );
        assert_eq!(r.remap(ClientRegistry::Attribute, 0), Some(23));

        assert_eq!(from.name_of(ClientRegistry::Item, 173), Some("grass"));
        assert_eq!(to.name_of(ClientRegistry::Item, 229), Some("short_grass"));
        assert_eq!(r.remap(ClientRegistry::Item, 173), Some(229));
        assert_eq!(r.remap(ClientRegistry::Item, 1), Some(1)); // stone

        assert_eq!(from.name_of(ClientRegistry::EntityType, 11), Some("cat"));
        assert_eq!(r.remap(ClientRegistry::EntityType, 11), Some(21));
        assert_eq!(r.remap(ClientRegistry::EntityType, 99), Some(131)); // tadpole
        assert_eq!(r.remap(ClientRegistry::ParticleType, 48), Some(66)); // poof

        assert_bed_unmapped(r, from);
        assert_chain_remapped(r, from);
        assert_unmapped(r, from, ClientRegistry::EntityType, "boat");

        assert_eq!(r.remap(ClientRegistry::DataComponentType, 0), None);
    }

    #[test]
    fn remap_1_20_2_anchors() {
        let (r, from, to) = setup(764);
        assert_pre_1_20_3_anchors(r, from, to);
        assert_round_trips(r, from, to);
    }

    #[test]
    fn remap_1_20_1_anchors() {
        let (r, from, to) = setup(763);
        assert_pre_1_20_3_anchors(r, from, to);
        assert_round_trips(r, from, to);
    }

    /// Anchor checks against the 1.20.4 -> 26.2 registry diff. This version
    /// predates data components (that registry is absent — every component
    /// remap is None) and 1.20.5/26.2 renamed or reshuffled heavily: the
    /// particle registry diverges at id 0.
    #[test]
    fn remap_1_20_4_anchors() {
        let (r, from, to) = setup(765);

        assert_eq!(
            from.name_of(ClientRegistry::Attribute, 11),
            Some("generic.max_health")
        );
        assert_eq!(r.remap(ClientRegistry::Attribute, 11), Some(23));

        assert_eq!(from.name_of(ClientRegistry::EntityType, 12), Some("cat"));
        assert_eq!(r.remap(ClientRegistry::EntityType, 12), Some(21));
        assert_eq!(r.remap(ClientRegistry::EntityType, 100), Some(131)); // tadpole

        assert_bed_unmapped(r, from);
        assert_chain_remapped(r, from);
        assert_unmapped(r, from, ClientRegistry::EntityType, "boat");
        assert_unmapped(r, from, ClientRegistry::SoundEvent, "item.goat_horn.play");

        // No component registry exists at 765.
        assert_eq!(r.remap(ClientRegistry::DataComponentType, 0), None);

        // 1.20.5 dropped ambient_entity_effect off the front of the particle
        // registry, shifting everything after it down one.
        assert_eq!(
            from.name_of(ClientRegistry::ParticleType, 0),
            Some("ambient_entity_effect")
        );
        assert_eq!(r.remap(ClientRegistry::ParticleType, 0), None);
        assert_eq!(r.remap(ClientRegistry::ParticleType, 1), Some(0)); // angry_villager

        assert_round_trips(r, from, to);
    }

    /// Every table parses and carries exactly the registries its version
    /// should, with unique names so ids and names resolve both ways. A
    /// generation slip fails here rather than silently remapping a whole
    /// registry to None. Anchor tests only cover the versions someone wrote
    /// one for.
    #[test]
    fn embedded_registry_tables_parse() {
        for e in EMBEDDED {
            let t = RegistryTable::for_protocol(e.version.protocol).unwrap();
            for reg in ClientRegistry::ALL {
                let names = t.names(reg);
                assert_eq!(
                    names.is_empty(),
                    e.version.protocol < reg.since(),
                    "{} {reg:?}",
                    e.version.name
                );
                let unique: std::collections::HashSet<_> = names.iter().collect();
                assert_eq!(unique.len(), names.len(), "{} {reg:?}", e.version.name);
            }
        }
    }

    #[test]
    fn native_identity() {
        let r = RegistryRemaps::to_native(NATIVE.protocol).unwrap();
        let names = RegistryTable::native().names(ClientRegistry::SoundEvent);
        assert_eq!(
            r.remap(ClientRegistry::SoundEvent, names.len() as u32 - 1),
            Some(names.len() as u32 - 1)
        );
    }
}
